/**
 * Geo identifiers for market cities — the county HUD uses to resolve
 * Fair Market Rent. The build-market-rents script matches each city to
 * a HUD entity by county name (within its state's FMR data), so this is
 * the bridge between MarketCity.slug and a real HUD lookup.
 *
 * `county` is the HUD county/independent-city name WITHOUT the "County"
 * suffix (e.g. "Franklin", "Baltimore city"). If a name doesn't match,
 * the script skips that city and the page keeps its estimate range —
 * a wrong/missing county degrades gracefully, it never breaks the page.
 *
 * `hudZip` (optional) is a representative central ZIP; reserved for
 * future ZIP-level Small Area FMR precision (not required for the
 * county-level snapshot).
 */

export type CityGeo = { county: string; hudZip?: string };

export const CITY_GEO: Record<string, CityGeo> = {
  columbus: { county: "Franklin" },
  cincinnati: { county: "Hamilton" },
  pittsburgh: { county: "Allegheny" },
  baltimore: { county: "Baltimore city" },
  "st-louis": { county: "St. Louis city" },
  milwaukee: { county: "Milwaukee" },
  "san-antonio": { county: "Bexar" },
  jacksonville: { county: "Duval" },
  birmingham: { county: "Jefferson" },
  louisville: { county: "Jefferson" },
  nashville: { county: "Davidson" },
  raleigh: { county: "Wake" },
  richmond: { county: "Richmond city" },
  columbia: { county: "Richland" },
  greenville: { county: "Greenville" },
  "oklahoma-city": { county: "Oklahoma" },
  tulsa: { county: "Tulsa" },
  omaha: { county: "Douglas" },
  "des-moines": { county: "Polk" },
  minneapolis: { county: "Hennepin" },
  buffalo: { county: "Erie" },
  rochester: { county: "Monroe" },
  orlando: { county: "Orange" },
  tucson: { county: "Pima" },
  "grand-rapids": { county: "Kent" },
  austin: { county: "Travis" },
  "fort-worth": { county: "Tarrant" },
  denver: { county: "Denver" },
  "colorado-springs": { county: "El Paso" },
  "salt-lake-city": { county: "Salt Lake" },
  boise: { county: "Ada" },
  albuquerque: { county: "Bernalillo" },
  "las-vegas": { county: "Clark" },
  sacramento: { county: "Sacramento" },
  portland: { county: "Multnomah" },
  chicago: { county: "Cook" },
  madison: { county: "Dane" },
  dayton: { county: "Montgomery" },
  akron: { county: "Summit" },
  toledo: { county: "Lucas" },
  lexington: { county: "Fayette" },
  knoxville: { county: "Knox" },
  chattanooga: { county: "Hamilton" },
  huntsville: { county: "Madison" },
  "little-rock": { county: "Pulaski" },
  "new-orleans": { county: "Orleans" },
  wichita: { county: "Sedgwick" },
  greensboro: { county: "Guilford" },
  "winston-salem": { county: "Forsyth" },
  savannah: { county: "Chatham" },
  "fort-wayne": { county: "Allen" },
  spokane: { county: "Spokane" },
  reno: { county: "Washoe" },
  "el-paso": { county: "El Paso" },
  "corpus-christi": { county: "Nueces" },
  "baton-rouge": { county: "East Baton Rouge" },
  shreveport: { county: "Caddo" },
  jackson: { county: "Hinds" },
  augusta: { county: "Richmond" },
  macon: { county: "Bibb" },
  lansing: { county: "Ingham" },
  "fort-collins": { county: "Larimer" },
  provo: { county: "Utah" },
  ogden: { county: "Weber" },
  lincoln: { county: "Lancaster" },
  "sioux-falls": { county: "Minnehaha" },
  fargo: { county: "Cass" },
  peoria: { county: "Peoria" },
  rockford: { county: "Winnebago" },
  "green-bay": { county: "Brown" },
  "fort-myers": { county: "Lee" },
  lakeland: { county: "Polk" },
  tallahassee: { county: "Leon" },
  pensacola: { county: "Escambia" },
  clarksville: { county: "Montgomery" },
  wilmington: { county: "New Castle" },
  allentown: { county: "Lehigh" },
  harrisburg: { county: "Dauphin" },
  scranton: { county: "Lackawanna" },
  worcester: { county: "Worcester" },
  hartford: { county: "Hartford" },
  "new-haven": { county: "New Haven" },
  providence: { county: "Providence" },
  manchester: { county: "Hillsborough" },
  syracuse: { county: "Onondaga" },
  albany: { county: "Albany" },
  youngstown: { county: "Mahoning" },
  canton: { county: "Stark" },
  evansville: { county: "Vanderburgh" },
  "south-bend": { county: "St. Joseph" },
  fresno: { county: "Fresno" },
  bakersfield: { county: "Kern" },
  stockton: { county: "San Joaquin" },
  modesto: { county: "Stanislaus" },
  salem: { county: "Marion" },
  tacoma: { county: "Pierce" },
  killeen: { county: "Bell" },
  waco: { county: "McLennan" },
  lubbock: { county: "Lubbock" },
  mobile: { county: "Mobile" },
  mcallen: { county: "Hidalgo" },
  brownsville: { county: "Cameron" },
  laredo: { county: "Webb" },
  amarillo: { county: "Potter" },
  beaumont: { county: "Jefferson" },
  denton: { county: "Denton" },
  mesa: { county: "Maricopa" },
  fayetteville: { county: "Washington" },
  "cedar-rapids": { county: "Linn" },
  davenport: { county: "Scott" },
  topeka: { county: "Shawnee" },
  olathe: { county: "Johnson" },
  champaign: { county: "Champaign" },
  flint: { county: "Genesee" },
  "ann-arbor": { county: "Washtenaw" },
  kalamazoo: { county: "Kalamazoo" },
  athens: { county: "Clarke" },
  tuscaloosa: { county: "Tuscaloosa" },
  montgomery: { county: "Montgomery" },
  gulfport: { county: "Harrison" },
  lafayette: { county: "Lafayette" },
  durham: { county: "Durham" },
  asheville: { county: "Buncombe" },
  norfolk: { county: "Norfolk city" },
  "virginia-beach": { county: "Virginia Beach city" },
  charleston: { county: "Charleston" },
  spartanburg: { county: "Spartanburg" },
  "myrtle-beach": { county: "Horry" },
  gainesville: { county: "Alachua" },
  ocala: { county: "Marion" },
  "daytona-beach": { county: "Volusia" },
  sarasota: { county: "Sarasota" },
  naples: { county: "Collier" },
  boulder: { county: "Boulder" },
  pueblo: { county: "Pueblo" },
  greeley: { county: "Weld" },
  eugene: { county: "Lane" },
  vancouver: { county: "Clark" },
  bellingham: { county: "Whatcom" },
  nampa: { county: "Canyon" },
  billings: { county: "Yellowstone" },
  lowell: { county: "Middlesex" },
  trenton: { county: "Mercer" },
  newark: { county: "Essex" },
  paterson: { county: "Passaic" },
  reading: { county: "Berks" },
  lancaster: { county: "Lancaster" },
  york: { county: "York" },
  erie: { county: "Erie" },
  anchorage: { county: "Anchorage" },
};
