/**
 * GENERATED by scripts/build-market-fmr-areas.ts — do not edit by hand.
 * The HUD Fair Market Rent area behind each market page's HUD figures, read
 * from HUD's FY2026 Fair Market Rent Documentation System (huduser.gov).
 * Each record's sourceUrl opens HUD's page for the county (New England: the
 * town), which names the area and shows its FMRs; safmrSourceUrl shows HUD's
 * ZIP-level Small Area FMRs where lib/markets/safmr-rents.ts has rows.
 */

export type HudFmrArea = {
  /** HUD's name for the FMR area, e.g. "Columbus, OH HUD Metro FMR Area". */
  areaName: string;
  /** The county (New England: town) whose HUD page was read, as HUD labels it. */
  countyName: string;
  /** HUD's documentation page for that county: the area's FMRs by bedroom count. */
  sourceUrl: string;
  /** HUD fiscal year of rent2br / rent3br. */
  year: number;
  rent2br: number;
  rent3br: number;
  /** The prior fiscal year's FMRs, from the same HUD page. */
  prior: { year: number; rent2br: number; rent3br: number } | null;
  /** HUD's Small Area FMR (ZIP) table for the area, when safmr-rents.ts has rows that match it. */
  safmrSourceUrl: string | null;
};

/** The day this file's pages were read from huduser.gov. */
export const HUD_FMR_AREAS_RETRIEVED_AT = "2026-09-27";

export const HUD_FMR_AREAS: Record<string, HudFmrArea> = {
  "columbus": {
    "areaName": "Columbus, OH HUD Metro FMR Area",
    "countyName": "Franklin County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3904999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1430,
    "rent3br": 1715,
    "prior": {
      "year": 2025,
      "rent2br": 1445,
      "rent3br": 1741
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3904999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "cincinnati": {
    "areaName": "Cincinnati, OH-KY-IN HUD Metro FMR Area",
    "countyName": "Hamilton County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3906199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1353,
    "rent3br": 1785,
    "prior": {
      "year": 2025,
      "rent2br": 1287,
      "rent3br": 1707
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3906199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "pittsburgh": {
    "areaName": "Pittsburgh, PA HUD Metro FMR Area",
    "countyName": "Allegheny County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4200399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1299,
    "rent3br": 1661,
    "prior": {
      "year": 2025,
      "rent2br": 1280,
      "rent3br": 1632
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4200399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "baltimore": {
    "areaName": "Baltimore-Columbia-Towson, MD MSA",
    "countyName": "Baltimore city, MD",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2451099999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1857,
    "rent3br": 2358,
    "prior": {
      "year": 2025,
      "rent2br": 1965,
      "rent3br": 2529
    },
    "safmrSourceUrl": null
  },
  "st-louis": {
    "areaName": "St. Louis, MO-IL HUD Metro FMR Area",
    "countyName": "St. Louis city, MO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2951099999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1218,
    "rent3br": 1568,
    "prior": {
      "year": 2025,
      "rent2br": 1215,
      "rent3br": 1570
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2951099999&year=2026&fmrtype=Final&selection_type=county"
  },
  "milwaukee": {
    "areaName": "Milwaukee-Waukesha, WI MSA",
    "countyName": "Milwaukee County, WI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5507999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1338,
    "rent3br": 1648,
    "prior": {
      "year": 2025,
      "rent2br": 1257,
      "rent3br": 1558
    },
    "safmrSourceUrl": null
  },
  "san-antonio": {
    "areaName": "San Antonio-New Braunfels, TX HUD Metro FMR Area",
    "countyName": "Bexar County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4802999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1426,
    "rent3br": 1830,
    "prior": {
      "year": 2025,
      "rent2br": 1501,
      "rent3br": 1907
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4802999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "jacksonville": {
    "areaName": "Jacksonville, FL HUD Metro FMR Area",
    "countyName": "Duval County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1203199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1658,
    "rent3br": 2043,
    "prior": {
      "year": 2025,
      "rent2br": 1730,
      "rent3br": 2163
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1203199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "birmingham": {
    "areaName": "Birmingham-Hoover, AL HUD Metro FMR Area",
    "countyName": "Jefferson County, AL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0107399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1266,
    "rent3br": 1583,
    "prior": {
      "year": 2025,
      "rent2br": 1267,
      "rent3br": 1583
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0107399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "louisville": {
    "areaName": "Louisville, KY-IN HUD Metro FMR Area",
    "countyName": "Jefferson County, KY",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2111199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1272,
    "rent3br": 1625,
    "prior": {
      "year": 2025,
      "rent2br": 1330,
      "rent3br": 1714
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2111199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "nashville": {
    "areaName": "Nashville-Davidson--Murfreesboro--Franklin, TN HUD Metro FMR Area",
    "countyName": "Davidson County, TN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4703799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1730,
    "rent3br": 2211,
    "prior": {
      "year": 2025,
      "rent2br": 1827,
      "rent3br": 2308
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4703799999&year=2026&fmrtype=Final&selection_type=county"
  },
  "raleigh": {
    "areaName": "Raleigh-Cary, NC MSA",
    "countyName": "Wake County, NC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3718399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1750,
    "rent3br": 2196,
    "prior": {
      "year": 2025,
      "rent2br": 1763,
      "rent3br": 2192
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3718399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "richmond": {
    "areaName": "Richmond, VA HUD Metro FMR Area",
    "countyName": "Richmond city, VA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5176099999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1655,
    "rent3br": 2072,
    "prior": {
      "year": 2025,
      "rent2br": 1711,
      "rent3br": 2166
    },
    "safmrSourceUrl": null
  },
  "columbia": {
    "areaName": "Columbia, SC HUD Metro FMR Area",
    "countyName": "Richland County, SC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4507999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1276,
    "rent3br": 1623,
    "prior": {
      "year": 2025,
      "rent2br": 1298,
      "rent3br": 1656
    },
    "safmrSourceUrl": null
  },
  "greenville": {
    "areaName": "Greenville-Mauldin-Easley, SC HUD Metro FMR Area",
    "countyName": "Greenville County, SC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4504599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1339,
    "rent3br": 1612,
    "prior": {
      "year": 2025,
      "rent2br": 1306,
      "rent3br": 1599
    },
    "safmrSourceUrl": null
  },
  "oklahoma-city": {
    "areaName": "Oklahoma City, OK HUD Metro FMR Area",
    "countyName": "Oklahoma County, OK",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4010999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1244,
    "rent3br": 1675,
    "prior": {
      "year": 2025,
      "rent2br": 1180,
      "rent3br": 1575
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4010999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "tulsa": {
    "areaName": "Tulsa, OK HUD Metro FMR Area",
    "countyName": "Tulsa County, OK",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4014399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1217,
    "rent3br": 1602,
    "prior": {
      "year": 2025,
      "rent2br": 1179,
      "rent3br": 1555
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4014399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "omaha": {
    "areaName": "Omaha-Council Bluffs, NE-IA HUD Metro FMR Area",
    "countyName": "Douglas County, NE",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3105599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1368,
    "rent3br": 1813,
    "prior": {
      "year": 2025,
      "rent2br": 1261,
      "rent3br": 1675
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3105599999&year=2026&fmrtype=Final&selection_type=county"
  },
  "des-moines": {
    "areaName": "Des Moines-West Des Moines, IA HUD Metro FMR Area",
    "countyName": "Polk County, IA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1915399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1318,
    "rent3br": 1794,
    "prior": {
      "year": 2025,
      "rent2br": 1216,
      "rent3br": 1632
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1915399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "minneapolis": {
    "areaName": "Minneapolis-St. Paul-Bloomington, MN-WI HUD Metro FMR Area",
    "countyName": "Hennepin County, MN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2705399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1709,
    "rent3br": 2262,
    "prior": {
      "year": 2025,
      "rent2br": 1685,
      "rent3br": 2244
    },
    "safmrSourceUrl": null
  },
  "buffalo": {
    "areaName": "Buffalo-Cheektowaga, NY MSA",
    "countyName": "Erie County, NY",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3602999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1343,
    "rent3br": 1640,
    "prior": {
      "year": 2025,
      "rent2br": 1176,
      "rent3br": 1438
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3602999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "rochester": {
    "areaName": "Rochester, NY MSA",
    "countyName": "Monroe County, NY",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3605599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1573,
    "rent3br": 1895,
    "prior": {
      "year": 2025,
      "rent2br": 1427,
      "rent3br": 1720
    },
    "safmrSourceUrl": null
  },
  "orlando": {
    "areaName": "Orlando-Kissimmee-Sanford, FL MSA",
    "countyName": "Orange County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1209599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1972,
    "rent3br": 2476,
    "prior": {
      "year": 2025,
      "rent2br": 1958,
      "rent3br": 2486
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1209599999&year=2026&fmrtype=Final&selection_type=county"
  },
  "tucson": {
    "areaName": "Tucson, AZ MSA",
    "countyName": "Pima County, AZ",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0401999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1402,
    "rent3br": 1950,
    "prior": {
      "year": 2025,
      "rent2br": 1373,
      "rent3br": 1924
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0401999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "grand-rapids": {
    "areaName": "Grand Rapids-Wyoming, MI HUD Metro FMR Area",
    "countyName": "Kent County, MI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2608199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1531,
    "rent3br": 1980,
    "prior": {
      "year": 2025,
      "rent2br": 1443,
      "rent3br": 1880
    },
    "safmrSourceUrl": null
  },
  "austin": {
    "areaName": "Austin-Round Rock-San Marcos, TX MSA",
    "countyName": "Travis County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4845399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1852,
    "rent3br": 2347,
    "prior": {
      "year": 2025,
      "rent2br": 1949,
      "rent3br": 2484
    },
    "safmrSourceUrl": null
  },
  "fort-worth": {
    "areaName": "Fort Worth-Arlington, TX HUD Metro FMR Area",
    "countyName": "Tarrant County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4843999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1723,
    "rent3br": 2273,
    "prior": {
      "year": 2025,
      "rent2br": 1705,
      "rent3br": 2256
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4843999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "denver": {
    "areaName": "Denver-Aurora-Centennial, CO MSA",
    "countyName": "Denver County, CO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0803199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2089,
    "rent3br": 2734,
    "prior": {
      "year": 2025,
      "rent2br": 2140,
      "rent3br": 2794
    },
    "safmrSourceUrl": null
  },
  "colorado-springs": {
    "areaName": "Colorado Springs, CO HUD Metro FMR Area",
    "countyName": "El Paso County, CO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0804199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1735,
    "rent3br": 2413,
    "prior": {
      "year": 2025,
      "rent2br": 1778,
      "rent3br": 2491
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0804199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "salt-lake-city": {
    "areaName": "Salt Lake City, UT HUD Metro FMR Area",
    "countyName": "Salt Lake County, UT",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4903599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1747,
    "rent3br": 2333,
    "prior": {
      "year": 2025,
      "rent2br": 1748,
      "rent3br": 2348
    },
    "safmrSourceUrl": null
  },
  "boise": {
    "areaName": "Boise City, ID HUD Metro FMR Area",
    "countyName": "Ada County, ID",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1600199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1655,
    "rent3br": 2318,
    "prior": {
      "year": 2025,
      "rent2br": 1838,
      "rent3br": 2575
    },
    "safmrSourceUrl": null
  },
  "albuquerque": {
    "areaName": "Albuquerque, NM MSA",
    "countyName": "Bernalillo County, NM",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3500199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1464,
    "rent3br": 2036,
    "prior": {
      "year": 2025,
      "rent2br": 1331,
      "rent3br": 1865
    },
    "safmrSourceUrl": null
  },
  "las-vegas": {
    "areaName": "Las Vegas-Henderson-North Las Vegas, NV MSA",
    "countyName": "Clark County, NV",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3200399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1735,
    "rent3br": 2413,
    "prior": {
      "year": 2025,
      "rent2br": 1750,
      "rent3br": 2452
    },
    "safmrSourceUrl": null
  },
  "sacramento": {
    "areaName": "Sacramento--Roseville--Arden-Arcade, CA HUD Metro FMR Area",
    "countyName": "Sacramento County, CA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0606799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2255,
    "rent3br": 3002,
    "prior": {
      "year": 2025,
      "rent2br": 2206,
      "rent3br": 2992
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0606799999&year=2026&fmrtype=Final&selection_type=county"
  },
  "portland": {
    "areaName": "Portland-Vancouver-Hillsboro, OR-WA MSA",
    "countyName": "Multnomah County, OR",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4105199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1922,
    "rent3br": 2619,
    "prior": {
      "year": 2025,
      "rent2br": 1997,
      "rent3br": 2739
    },
    "safmrSourceUrl": null
  },
  "chicago": {
    "areaName": "Chicago-Joliet-Naperville, IL HUD Metro FMR Area",
    "countyName": "Cook County, IL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1703199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1781,
    "rent3br": 2294,
    "prior": {
      "year": 2025,
      "rent2br": 1761,
      "rent3br": 2262
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1703199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "madison": {
    "areaName": "Madison, WI HUD Metro FMR Area",
    "countyName": "Dane County, WI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5502599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1694,
    "rent3br": 2236,
    "prior": {
      "year": 2025,
      "rent2br": 1472,
      "rent3br": 1935
    },
    "safmrSourceUrl": null
  },
  "dayton": {
    "areaName": "Dayton-Kettering-Beavercreek, OH MSA",
    "countyName": "Montgomery County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3911399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1273,
    "rent3br": 1651,
    "prior": {
      "year": 2025,
      "rent2br": 1077,
      "rent3br": 1390
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3911399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "akron": {
    "areaName": "Akron, OH MSA",
    "countyName": "Summit County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3915399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1268,
    "rent3br": 1547,
    "prior": {
      "year": 2025,
      "rent2br": 1131,
      "rent3br": 1398
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3915399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "toledo": {
    "areaName": "Toledo, OH MSA",
    "countyName": "Lucas County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3909599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1076,
    "rent3br": 1380,
    "prior": {
      "year": 2025,
      "rent2br": 1056,
      "rent3br": 1371
    },
    "safmrSourceUrl": null
  },
  "lexington": {
    "areaName": "Lexington-Fayette, KY MSA",
    "countyName": "Fayette County, KY",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2106799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1272,
    "rent3br": 1743,
    "prior": {
      "year": 2025,
      "rent2br": 1165,
      "rent3br": 1583
    },
    "safmrSourceUrl": null
  },
  "knoxville": {
    "areaName": "Knoxville, TN HUD Metro FMR Area",
    "countyName": "Knox County, TN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4709399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1471,
    "rent3br": 1864,
    "prior": {
      "year": 2025,
      "rent2br": 1548,
      "rent3br": 1989
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4709399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "chattanooga": {
    "areaName": "Chattanooga, TN-GA MSA",
    "countyName": "Hamilton County, TN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4706599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1390,
    "rent3br": 1734,
    "prior": {
      "year": 2025,
      "rent2br": 1426,
      "rent3br": 1796
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4706599999&year=2026&fmrtype=Final&selection_type=county"
  },
  "huntsville": {
    "areaName": "Huntsville, AL MSA",
    "countyName": "Madison County, AL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0108999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1310,
    "rent3br": 1690,
    "prior": {
      "year": 2025,
      "rent2br": 1248,
      "rent3br": 1609
    },
    "safmrSourceUrl": null
  },
  "little-rock": {
    "areaName": "Little Rock-North Little Rock-Conway, AR HUD Metro FMR Area",
    "countyName": "Pulaski County, AR",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0511999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1147,
    "rent3br": 1540,
    "prior": {
      "year": 2025,
      "rent2br": 1032,
      "rent3br": 1376
    },
    "safmrSourceUrl": null
  },
  "new-orleans": {
    "areaName": "New Orleans-Metairie, LA HUD Metro FMR Area",
    "countyName": "Orleans Parish, LA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2207199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1331,
    "rent3br": 1701,
    "prior": {
      "year": 2025,
      "rent2br": 1478,
      "rent3br": 1889
    },
    "safmrSourceUrl": null
  },
  "wichita": {
    "areaName": "Wichita, KS HUD Metro FMR Area",
    "countyName": "Sedgwick County, KS",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2017399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1099,
    "rent3br": 1444,
    "prior": {
      "year": 2025,
      "rent2br": 995,
      "rent3br": 1305
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2017399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "greensboro": {
    "areaName": "Greensboro-High Point, NC HUD Metro FMR Area",
    "countyName": "Guilford County, NC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3708199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1330,
    "rent3br": 1703,
    "prior": {
      "year": 2025,
      "rent2br": 1150,
      "rent3br": 1463
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3708199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "winston-salem": {
    "areaName": "Winston-Salem, NC HUD Metro FMR Area",
    "countyName": "Forsyth County, NC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3706799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1232,
    "rent3br": 1607,
    "prior": {
      "year": 2025,
      "rent2br": 1163,
      "rent3br": 1526
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3706799999&year=2026&fmrtype=Final&selection_type=county"
  },
  "savannah": {
    "areaName": "Savannah, GA MSA",
    "countyName": "Chatham County, GA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1305199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1680,
    "rent3br": 2235,
    "prior": {
      "year": 2025,
      "rent2br": 1584,
      "rent3br": 2131
    },
    "safmrSourceUrl": null
  },
  "fort-wayne": {
    "areaName": "Fort Wayne, IN HUD Metro FMR Area",
    "countyName": "Allen County, IN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1800399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1113,
    "rent3br": 1381,
    "prior": {
      "year": 2025,
      "rent2br": 1199,
      "rent3br": 1512
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1800399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "spokane": {
    "areaName": "Spokane, WA HUD Metro FMR Area",
    "countyName": "Spokane County, WA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5306399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1531,
    "rent3br": 2088,
    "prior": {
      "year": 2025,
      "rent2br": 1444,
      "rent3br": 1997
    },
    "safmrSourceUrl": null
  },
  "reno": {
    "areaName": "Reno, NV HUD Metro FMR Area",
    "countyName": "Washoe County, NV",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3203199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1870,
    "rent3br": 2539,
    "prior": {
      "year": 2025,
      "rent2br": 1722,
      "rent3br": 2384
    },
    "safmrSourceUrl": null
  },
  "el-paso": {
    "areaName": "El Paso, TX HUD Metro FMR Area",
    "countyName": "El Paso County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4814199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1191,
    "rent3br": 1633,
    "prior": {
      "year": 2025,
      "rent2br": 1192,
      "rent3br": 1647
    },
    "safmrSourceUrl": null
  },
  "corpus-christi": {
    "areaName": "Corpus Christi, TX HUD Metro FMR Area",
    "countyName": "Nueces County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4835599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1366,
    "rent3br": 1796,
    "prior": {
      "year": 2025,
      "rent2br": 1390,
      "rent3br": 1816
    },
    "safmrSourceUrl": null
  },
  "baton-rouge": {
    "areaName": "Baton Rouge, LA HUD Metro FMR Area",
    "countyName": "East Baton Rouge Parish, LA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2203399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1204,
    "rent3br": 1511,
    "prior": {
      "year": 2025,
      "rent2br": 1222,
      "rent3br": 1528
    },
    "safmrSourceUrl": null
  },
  "shreveport": {
    "areaName": "Shreveport-Bossier City, LA MSA",
    "countyName": "Caddo Parish, LA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2201799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1111,
    "rent3br": 1458,
    "prior": {
      "year": 2025,
      "rent2br": 1017,
      "rent3br": 1317
    },
    "safmrSourceUrl": null
  },
  "jackson": {
    "areaName": "Jackson, MS HUD Metro FMR Area",
    "countyName": "Hinds County, MS",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2804999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1288,
    "rent3br": 1544,
    "prior": {
      "year": 2025,
      "rent2br": 1232,
      "rent3br": 1484
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2804999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "augusta": {
    "areaName": "Augusta-Richmond County, GA-SC HUD Metro FMR Area",
    "countyName": "Richmond County, GA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1324599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1261,
    "rent3br": 1627,
    "prior": {
      "year": 2025,
      "rent2br": 1175,
      "rent3br": 1545
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1324599999&year=2026&fmrtype=Final&selection_type=county"
  },
  "macon": {
    "areaName": "Macon-Bibb County, GA HUD Metro FMR Area",
    "countyName": "Bibb County, GA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1302199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1307,
    "rent3br": 1567,
    "prior": {
      "year": 2025,
      "rent2br": 1252,
      "rent3br": 1508
    },
    "safmrSourceUrl": null
  },
  "lansing": {
    "areaName": "Lansing-East Lansing, MI MSA",
    "countyName": "Ingham County, MI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2606599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1268,
    "rent3br": 1627,
    "prior": {
      "year": 2025,
      "rent2br": 1127,
      "rent3br": 1465
    },
    "safmrSourceUrl": null
  },
  "fort-collins": {
    "areaName": "Fort Collins-Loveland, CO MSA",
    "countyName": "Larimer County, CO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0806999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1732,
    "rent3br": 2385,
    "prior": {
      "year": 2025,
      "rent2br": 1695,
      "rent3br": 2375
    },
    "safmrSourceUrl": null
  },
  "provo": {
    "areaName": "Provo-Orem-Lehi, UT MSA",
    "countyName": "Utah County, UT",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4904999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1460,
    "rent3br": 2031,
    "prior": {
      "year": 2025,
      "rent2br": 1355,
      "rent3br": 1899
    },
    "safmrSourceUrl": null
  },
  "ogden": {
    "areaName": "Ogden, UT MSA",
    "countyName": "Weber County, UT",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4905799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1614,
    "rent3br": 2163,
    "prior": {
      "year": 2025,
      "rent2br": 1532,
      "rent3br": 2055
    },
    "safmrSourceUrl": null
  },
  "lincoln": {
    "areaName": "Lincoln, NE HUD Metro FMR Area",
    "countyName": "Lancaster County, NE",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3110999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1141,
    "rent3br": 1587,
    "prior": {
      "year": 2025,
      "rent2br": 1125,
      "rent3br": 1576
    },
    "safmrSourceUrl": null
  },
  "sioux-falls": {
    "areaName": "Sioux Falls, SD HUD Metro FMR Area",
    "countyName": "Minnehaha County, SD",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4609999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1156,
    "rent3br": 1586,
    "prior": {
      "year": 2025,
      "rent2br": 1030,
      "rent3br": 1412
    },
    "safmrSourceUrl": null
  },
  "fargo": {
    "areaName": "Fargo, ND-MN MSA",
    "countyName": "Cass County, ND",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3801799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1112,
    "rent3br": 1547,
    "prior": {
      "year": 2025,
      "rent2br": 1012,
      "rent3br": 1418
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3801799999&year=2026&fmrtype=Final&selection_type=county"
  },
  "peoria": {
    "areaName": "Peoria, IL MSA",
    "countyName": "Peoria County, IL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1714399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1039,
    "rent3br": 1346,
    "prior": {
      "year": 2025,
      "rent2br": 1003,
      "rent3br": 1300
    },
    "safmrSourceUrl": null
  },
  "rockford": {
    "areaName": "Rockford, IL MSA",
    "countyName": "Winnebago County, IL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1720199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1175,
    "rent3br": 1555,
    "prior": {
      "year": 2025,
      "rent2br": 1181,
      "rent3br": 1561
    },
    "safmrSourceUrl": null
  },
  "green-bay": {
    "areaName": "Green Bay, WI HUD Metro FMR Area",
    "countyName": "Brown County, WI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5500999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1164,
    "rent3br": 1545,
    "prior": {
      "year": 2025,
      "rent2br": 1147,
      "rent3br": 1521
    },
    "safmrSourceUrl": null
  },
  "fort-myers": {
    "areaName": "Cape Coral-Fort Myers, FL MSA",
    "countyName": "Lee County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1207199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1961,
    "rent3br": 2560,
    "prior": {
      "year": 2025,
      "rent2br": 1843,
      "rent3br": 2422
    },
    "safmrSourceUrl": null
  },
  "lakeland": {
    "areaName": "Lakeland-Winter Haven, FL MSA",
    "countyName": "Polk County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1210599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1497,
    "rent3br": 2023,
    "prior": {
      "year": 2025,
      "rent2br": 1337,
      "rent3br": 1797
    },
    "safmrSourceUrl": null
  },
  "tallahassee": {
    "areaName": "Tallahassee, FL HUD Metro FMR Area",
    "countyName": "Leon County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1207399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1352,
    "rent3br": 1674,
    "prior": {
      "year": 2025,
      "rent2br": 1321,
      "rent3br": 1664
    },
    "safmrSourceUrl": null
  },
  "pensacola": {
    "areaName": "Pensacola-Ferry Pass-Brent, FL MSA",
    "countyName": "Escambia County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1203399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1471,
    "rent3br": 1952,
    "prior": {
      "year": 2025,
      "rent2br": 1605,
      "rent3br": 2147
    },
    "safmrSourceUrl": null
  },
  "clarksville": {
    "areaName": "Clarksville, TN-KY HUD Metro FMR Area",
    "countyName": "Montgomery County, TN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4712599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1346,
    "rent3br": 1871,
    "prior": {
      "year": 2025,
      "rent2br": 1229,
      "rent3br": 1722
    },
    "safmrSourceUrl": null
  },
  "wilmington": {
    "areaName": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA",
    "countyName": "New Castle County, DE",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1000399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1810,
    "rent3br": 2170,
    "prior": {
      "year": 2025,
      "rent2br": 1802,
      "rent3br": 2171
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1000399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "allentown": {
    "areaName": "Allentown-Bethlehem-Easton, PA HUD Metro FMR Area",
    "countyName": "Lehigh County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4207799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1634,
    "rent3br": 2087,
    "prior": {
      "year": 2025,
      "rent2br": 1507,
      "rent3br": 1924
    },
    "safmrSourceUrl": null
  },
  "harrisburg": {
    "areaName": "Harrisburg-Carlisle, PA MSA",
    "countyName": "Dauphin County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4204399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1493,
    "rent3br": 1920,
    "prior": {
      "year": 2025,
      "rent2br": 1371,
      "rent3br": 1763
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4204399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "scranton": {
    "areaName": "Scranton--Wilkes-Barre, PA MSA",
    "countyName": "Lackawanna County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4206999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1252,
    "rent3br": 1631,
    "prior": {
      "year": 2025,
      "rent2br": 1123,
      "rent3br": 1462
    },
    "safmrSourceUrl": null
  },
  "worcester": {
    "areaName": "Worcester, MA HUD Metro FMR Area",
    "countyName": "Worcester city (Worcester County), MA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2502782000&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2056,
    "rent3br": 2548,
    "prior": {
      "year": 2025,
      "rent2br": 1854,
      "rent3br": 2265
    },
    "safmrSourceUrl": null
  },
  "hartford": {
    "areaName": "Hartford-West Hartford-East Hartford, CT MSA",
    "countyName": "Hartford town (Capitol Planning Region), CT",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0911037070&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1865,
    "rent3br": 2236,
    "prior": {
      "year": 2025,
      "rent2br": 1653,
      "rent3br": 1992
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0911037070&year=2026&fmrtype=Final&selection_type=county"
  },
  "new-haven": {
    "areaName": "New Haven, CT MSA",
    "countyName": "New Haven town (South Central Connecticut Planning Region), CT",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0917052070&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1969,
    "rent3br": 2433,
    "prior": {
      "year": 2025,
      "rent2br": 1867,
      "rent3br": 2319
    },
    "safmrSourceUrl": null
  },
  "providence": {
    "areaName": "Providence-Fall River, RI-MA HUD Metro FMR Area",
    "countyName": "Providence city (Providence County), RI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4400759000&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1729,
    "rent3br": 2087,
    "prior": {
      "year": 2025,
      "rent2br": 1614,
      "rent3br": 1945
    },
    "safmrSourceUrl": null
  },
  "manchester": {
    "areaName": "Manchester, NH HUD Metro FMR Area",
    "countyName": "Manchester city (Hillsborough County), NH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3301145140&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2037,
    "rent3br": 2442,
    "prior": {
      "year": 2025,
      "rent2br": 1948,
      "rent3br": 2347
    },
    "safmrSourceUrl": null
  },
  "syracuse": {
    "areaName": "Syracuse, NY MSA",
    "countyName": "Onondaga County, NY",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3606799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1392,
    "rent3br": 1691,
    "prior": {
      "year": 2025,
      "rent2br": 1321,
      "rent3br": 1616
    },
    "safmrSourceUrl": null
  },
  "albany": {
    "areaName": "Albany-Schenectady-Troy, NY MSA",
    "countyName": "Albany County, NY",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3600199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1702,
    "rent3br": 2041,
    "prior": {
      "year": 2025,
      "rent2br": 1487,
      "rent3br": 1792
    },
    "safmrSourceUrl": null
  },
  "youngstown": {
    "areaName": "Youngstown-Warren, OH MSA",
    "countyName": "Mahoning County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3909999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 973,
    "rent3br": 1270,
    "prior": {
      "year": 2025,
      "rent2br": 884,
      "rent3br": 1159
    },
    "safmrSourceUrl": null
  },
  "canton": {
    "areaName": "Canton-Massillon, OH MSA",
    "countyName": "Stark County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3915199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1086,
    "rent3br": 1371,
    "prior": {
      "year": 2025,
      "rent2br": 978,
      "rent3br": 1229
    },
    "safmrSourceUrl": null
  },
  "evansville": {
    "areaName": "Evansville, IN MSA",
    "countyName": "Vanderburgh County, IN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1816399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1113,
    "rent3br": 1370,
    "prior": {
      "year": 2025,
      "rent2br": 1054,
      "rent3br": 1300
    },
    "safmrSourceUrl": null
  },
  "south-bend": {
    "areaName": "South Bend-Mishawaka, IN HUD Metro FMR Area",
    "countyName": "St. Joseph County, IN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1814199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1292,
    "rent3br": 1567,
    "prior": {
      "year": 2025,
      "rent2br": 1095,
      "rent3br": 1350
    },
    "safmrSourceUrl": null
  },
  "fresno": {
    "areaName": "Fresno, CA HUD Metro FMR Area",
    "countyName": "Fresno County, CA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0601999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1664,
    "rent3br": 2314,
    "prior": {
      "year": 2025,
      "rent2br": 1505,
      "rent3br": 2109
    },
    "safmrSourceUrl": null
  },
  "bakersfield": {
    "areaName": "Bakersfield-Delano, CA MSA",
    "countyName": "Kern County, CA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0602999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1483,
    "rent3br": 2062,
    "prior": {
      "year": 2025,
      "rent2br": 1380,
      "rent3br": 1934
    },
    "safmrSourceUrl": null
  },
  "stockton": {
    "areaName": "Stockton-Lodi, CA MSA",
    "countyName": "San Joaquin County, CA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0607799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1742,
    "rent3br": 2423,
    "prior": {
      "year": 2025,
      "rent2br": 1736,
      "rent3br": 2433
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0607799999&year=2026&fmrtype=Final&selection_type=county"
  },
  "modesto": {
    "areaName": "Modesto, CA MSA",
    "countyName": "Stanislaus County, CA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0609999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1758,
    "rent3br": 2442,
    "prior": {
      "year": 2025,
      "rent2br": 1566,
      "rent3br": 2194
    },
    "safmrSourceUrl": null
  },
  "salem": {
    "areaName": "Salem, OR MSA",
    "countyName": "Marion County, OR",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4104799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1560,
    "rent3br": 2159,
    "prior": {
      "year": 2025,
      "rent2br": 1543,
      "rent3br": 2148
    },
    "safmrSourceUrl": null
  },
  "tacoma": {
    "areaName": "Tacoma, WA HUD Metro FMR Area",
    "countyName": "Pierce County, WA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5305399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1971,
    "rent3br": 2733,
    "prior": {
      "year": 2025,
      "rent2br": 2057,
      "rent3br": 2882
    },
    "safmrSourceUrl": null
  },
  "killeen": {
    "areaName": "Killeen-Temple, TX HUD Metro FMR Area",
    "countyName": "Bell County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4802799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1233,
    "rent3br": 1711,
    "prior": {
      "year": 2025,
      "rent2br": 1172,
      "rent3br": 1631
    },
    "safmrSourceUrl": null
  },
  "waco": {
    "areaName": "Waco, TX HUD Metro FMR Area",
    "countyName": "McLennan County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4830999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1240,
    "rent3br": 1599,
    "prior": {
      "year": 2025,
      "rent2br": 1377,
      "rent3br": 1776
    },
    "safmrSourceUrl": null
  },
  "lubbock": {
    "areaName": "Lubbock, TX HUD Metro FMR Area",
    "countyName": "Lubbock County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4830399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1175,
    "rent3br": 1634,
    "prior": {
      "year": 2025,
      "rent2br": 1192,
      "rent3br": 1658
    },
    "safmrSourceUrl": null
  },
  "mobile": {
    "areaName": "Mobile, AL MSA",
    "countyName": "Mobile County, AL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0109799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1083,
    "rent3br": 1414,
    "prior": {
      "year": 2025,
      "rent2br": 1094,
      "rent3br": 1441
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0109799999&year=2026&fmrtype=Final&selection_type=county"
  },
  "mcallen": {
    "areaName": "McAllen-Edinburg-Mission, TX MSA",
    "countyName": "Hidalgo County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4821599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1060,
    "rent3br": 1376,
    "prior": {
      "year": 2025,
      "rent2br": 992,
      "rent3br": 1290
    },
    "safmrSourceUrl": null
  },
  "brownsville": {
    "areaName": "Brownsville-Harlingen, TX MSA",
    "countyName": "Cameron County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4806199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1047,
    "rent3br": 1414,
    "prior": {
      "year": 2025,
      "rent2br": 948,
      "rent3br": 1264
    },
    "safmrSourceUrl": null
  },
  "laredo": {
    "areaName": "Laredo, TX MSA",
    "countyName": "Webb County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4847999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1161,
    "rent3br": 1499,
    "prior": {
      "year": 2025,
      "rent2br": 1173,
      "rent3br": 1493
    },
    "safmrSourceUrl": null
  },
  "amarillo": {
    "areaName": "Amarillo, TX HUD Metro FMR Area",
    "countyName": "Potter County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4837599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1106,
    "rent3br": 1503,
    "prior": {
      "year": 2025,
      "rent2br": 1158,
      "rent3br": 1592
    },
    "safmrSourceUrl": null
  },
  "beaumont": {
    "areaName": "Beaumont-Port Arthur, TX MSA",
    "countyName": "Jefferson County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4824599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1103,
    "rent3br": 1446,
    "prior": {
      "year": 2025,
      "rent2br": 1113,
      "rent3br": 1460
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4824599999&year=2026&fmrtype=Final&selection_type=county"
  },
  "denton": {
    "areaName": "Dallas, TX HUD Metro FMR Area",
    "countyName": "Denton County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4812199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1931,
    "rent3br": 2431,
    "prior": {
      "year": 2025,
      "rent2br": 1884,
      "rent3br": 2361
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4812199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "mesa": {
    "areaName": "Phoenix-Mesa-Chandler, AZ MSA",
    "countyName": "Maricopa County, AZ",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0401399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1839,
    "rent3br": 2452,
    "prior": {
      "year": 2025,
      "rent2br": 1950,
      "rent3br": 2624
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0401399999&year=2026&fmrtype=Final&selection_type=county"
  },
  "fayetteville": {
    "areaName": "Fayetteville-Springdale-Rogers, AR MSA",
    "countyName": "Washington County, AR",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0514399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1347,
    "rent3br": 1873,
    "prior": {
      "year": 2025,
      "rent2br": 1111,
      "rent3br": 1557
    },
    "safmrSourceUrl": null
  },
  "cedar-rapids": {
    "areaName": "Cedar Rapids, IA HUD Metro FMR Area",
    "countyName": "Linn County, IA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1911399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1071,
    "rent3br": 1490,
    "prior": {
      "year": 2025,
      "rent2br": 993,
      "rent3br": 1391
    },
    "safmrSourceUrl": null
  },
  "davenport": {
    "areaName": "Davenport-Moline-Rock Island, IA-IL MSA",
    "countyName": "Scott County, IA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1916399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1143,
    "rent3br": 1498,
    "prior": {
      "year": 2025,
      "rent2br": 1025,
      "rent3br": 1336
    },
    "safmrSourceUrl": null
  },
  "topeka": {
    "areaName": "Topeka, KS MSA",
    "countyName": "Shawnee County, KS",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2017799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1057,
    "rent3br": 1392,
    "prior": {
      "year": 2025,
      "rent2br": 985,
      "rent3br": 1280
    },
    "safmrSourceUrl": null
  },
  "olathe": {
    "areaName": "Kansas City, MO-KS HUD Metro FMR Area",
    "countyName": "Johnson County, KS",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2009199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1358,
    "rent3br": 1769,
    "prior": {
      "year": 2025,
      "rent2br": 1346,
      "rent3br": 1756
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2009199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "champaign": {
    "areaName": "Champaign-Urbana, IL HUD Metro FMR Area",
    "countyName": "Champaign County, IL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1701999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1122,
    "rent3br": 1436,
    "prior": {
      "year": 2025,
      "rent2br": 1080,
      "rent3br": 1405
    },
    "safmrSourceUrl": null
  },
  "flint": {
    "areaName": "Flint, MI MSA",
    "countyName": "Genesee County, MI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2604999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1033,
    "rent3br": 1272,
    "prior": {
      "year": 2025,
      "rent2br": 986,
      "rent3br": 1215
    },
    "safmrSourceUrl": null
  },
  "ann-arbor": {
    "areaName": "Ann Arbor, MI MSA",
    "countyName": "Washtenaw County, MI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2616199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1656,
    "rent3br": 1986,
    "prior": {
      "year": 2025,
      "rent2br": 1607,
      "rent3br": 1936
    },
    "safmrSourceUrl": null
  },
  "kalamazoo": {
    "areaName": "Kalamazoo-Portage, MI MSA",
    "countyName": "Kalamazoo County, MI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2607799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1162,
    "rent3br": 1531,
    "prior": {
      "year": 2025,
      "rent2br": 1181,
      "rent3br": 1564
    },
    "safmrSourceUrl": null
  },
  "athens": {
    "areaName": "Athens-Clarke County, GA MSA",
    "countyName": "Clarke County, GA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1305999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1331,
    "rent3br": 1734,
    "prior": {
      "year": 2025,
      "rent2br": 1225,
      "rent3br": 1627
    },
    "safmrSourceUrl": null
  },
  "tuscaloosa": {
    "areaName": "Tuscaloosa, AL HUD Metro FMR Area",
    "countyName": "Tuscaloosa County, AL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0112599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1169,
    "rent3br": 1490,
    "prior": {
      "year": 2025,
      "rent2br": 1138,
      "rent3br": 1450
    },
    "safmrSourceUrl": null
  },
  "montgomery": {
    "areaName": "Montgomery, AL MSA",
    "countyName": "Montgomery County, AL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0110199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1016,
    "rent3br": 1304,
    "prior": {
      "year": 2025,
      "rent2br": 1055,
      "rent3br": 1345
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0110199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "gulfport": {
    "areaName": "Gulfport-Biloxi, MS HUD Metro FMR Area",
    "countyName": "Harrison County, MS",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2804799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1140,
    "rent3br": 1471,
    "prior": {
      "year": 2025,
      "rent2br": 1117,
      "rent3br": 1446
    },
    "safmrSourceUrl": null
  },
  "lafayette": {
    "areaName": "Lafayette, LA HUD Metro FMR Area",
    "countyName": "Lafayette Parish, LA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2205599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1019,
    "rent3br": 1301,
    "prior": {
      "year": 2025,
      "rent2br": 1052,
      "rent3br": 1322
    },
    "safmrSourceUrl": null
  },
  "durham": {
    "areaName": "Durham-Chapel Hill, NC HUD Metro FMR Area",
    "countyName": "Durham County, NC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3706399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1711,
    "rent3br": 2117,
    "prior": {
      "year": 2025,
      "rent2br": 1872,
      "rent3br": 2334
    },
    "safmrSourceUrl": null
  },
  "asheville": {
    "areaName": "Asheville, NC MSA",
    "countyName": "Buncombe County, NC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3702199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1835,
    "rent3br": 2231,
    "prior": {
      "year": 2025,
      "rent2br": 1512,
      "rent3br": 1944
    },
    "safmrSourceUrl": null
  },
  "norfolk": {
    "areaName": "Virginia Beach-Norfolk-Newport News, VA-NC HUD Metro FMR Area",
    "countyName": "Norfolk city, VA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5171099999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1713,
    "rent3br": 2376,
    "prior": {
      "year": 2025,
      "rent2br": 1696,
      "rent3br": 2361
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5171099999&year=2026&fmrtype=Final&selection_type=county"
  },
  "virginia-beach": {
    "areaName": "Virginia Beach-Norfolk-Newport News, VA-NC HUD Metro FMR Area",
    "countyName": "Virginia Beach city, VA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5181099999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1713,
    "rent3br": 2376,
    "prior": {
      "year": 2025,
      "rent2br": 1696,
      "rent3br": 2361
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5181099999&year=2026&fmrtype=Final&selection_type=county"
  },
  "charleston": {
    "areaName": "Charleston-North Charleston, SC MSA",
    "countyName": "Charleston County, SC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4501999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1787,
    "rent3br": 2222,
    "prior": {
      "year": 2025,
      "rent2br": 1820,
      "rent3br": 2255
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4501999999&year=2026&fmrtype=Final&selection_type=county"
  },
  "spartanburg": {
    "areaName": "Spartanburg, SC HUD Metro FMR Area",
    "countyName": "Spartanburg County, SC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4508399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1187,
    "rent3br": 1439,
    "prior": {
      "year": 2025,
      "rent2br": 1211,
      "rent3br": 1493
    },
    "safmrSourceUrl": null
  },
  "myrtle-beach": {
    "areaName": "Myrtle Beach-North Myrtle Beach-Conway, SC HUD Metro FMR Area",
    "countyName": "Horry County, SC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4505199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1465,
    "rent3br": 1805,
    "prior": {
      "year": 2025,
      "rent2br": 1406,
      "rent3br": 1771
    },
    "safmrSourceUrl": null
  },
  "gainesville": {
    "areaName": "Gainesville, FL HUD Metro FMR Area",
    "countyName": "Alachua County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1200199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1493,
    "rent3br": 1868,
    "prior": {
      "year": 2025,
      "rent2br": 1583,
      "rent3br": 2016
    },
    "safmrSourceUrl": null
  },
  "ocala": {
    "areaName": "Ocala, FL MSA",
    "countyName": "Marion County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1208399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1373,
    "rent3br": 1772,
    "prior": {
      "year": 2025,
      "rent2br": 1323,
      "rent3br": 1691
    },
    "safmrSourceUrl": null
  },
  "daytona-beach": {
    "areaName": "Deltona-Daytona Beach-Ormond Beach, FL HUD Metro FMR Area",
    "countyName": "Volusia County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1212799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1700,
    "rent3br": 2241,
    "prior": {
      "year": 2025,
      "rent2br": 1718,
      "rent3br": 2260
    },
    "safmrSourceUrl": null
  },
  "sarasota": {
    "areaName": "North Port-Bradenton-Sarasota, FL MSA",
    "countyName": "Sarasota County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1211599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1958,
    "rent3br": 2537,
    "prior": {
      "year": 2025,
      "rent2br": 1846,
      "rent3br": 2425
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1211599999&year=2026&fmrtype=Final&selection_type=county"
  },
  "naples": {
    "areaName": "Naples-Marco Island, FL MSA",
    "countyName": "Collier County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1202199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1986,
    "rent3br": 2581,
    "prior": {
      "year": 2025,
      "rent2br": 1860,
      "rent3br": 2453
    },
    "safmrSourceUrl": null
  },
  "boulder": {
    "areaName": "Boulder, CO MSA",
    "countyName": "Boulder County, CO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0801399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2124,
    "rent3br": 2820,
    "prior": {
      "year": 2025,
      "rent2br": 2059,
      "rent3br": 2704
    },
    "safmrSourceUrl": null
  },
  "pueblo": {
    "areaName": "Pueblo, CO MSA",
    "countyName": "Pueblo County, CO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0810199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1269,
    "rent3br": 1617,
    "prior": {
      "year": 2025,
      "rent2br": 1258,
      "rent3br": 1626
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0810199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "greeley": {
    "areaName": "Greeley, CO MSA",
    "countyName": "Weld County, CO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0812399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1563,
    "rent3br": 2174,
    "prior": {
      "year": 2025,
      "rent2br": 1528,
      "rent3br": 2141
    },
    "safmrSourceUrl": null
  },
  "eugene": {
    "areaName": "Eugene-Springfield, OR MSA",
    "countyName": "Lane County, OR",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4103999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1688,
    "rent3br": 2348,
    "prior": {
      "year": 2025,
      "rent2br": 1495,
      "rent3br": 2095
    },
    "safmrSourceUrl": null
  },
  "vancouver": {
    "areaName": "Portland-Vancouver-Hillsboro, OR-WA MSA",
    "countyName": "Clark County, WA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5301199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1922,
    "rent3br": 2619,
    "prior": {
      "year": 2025,
      "rent2br": 1997,
      "rent3br": 2739
    },
    "safmrSourceUrl": null
  },
  "bellingham": {
    "areaName": "Bellingham, WA MSA",
    "countyName": "Whatcom County, WA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=5307399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1794,
    "rent3br": 2495,
    "prior": {
      "year": 2025,
      "rent2br": 1642,
      "rent3br": 2301
    },
    "safmrSourceUrl": null
  },
  "nampa": {
    "areaName": "Boise City, ID HUD Metro FMR Area",
    "countyName": "Canyon County, ID",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1602799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1655,
    "rent3br": 2318,
    "prior": {
      "year": 2025,
      "rent2br": 1838,
      "rent3br": 2575
    },
    "safmrSourceUrl": null
  },
  "billings": {
    "areaName": "Billings, MT HUD Metro FMR Area",
    "countyName": "Yellowstone County, MT",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3011199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1417,
    "rent3br": 1951,
    "prior": {
      "year": 2025,
      "rent2br": 1373,
      "rent3br": 1888
    },
    "safmrSourceUrl": null
  },
  "lowell": {
    "areaName": "Lowell, MA HUD Metro FMR Area",
    "countyName": "Lowell city (Middlesex County), MA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2501737000&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2351,
    "rent3br": 2819,
    "prior": {
      "year": 2025,
      "rent2br": 2242,
      "rent3br": 2701
    },
    "safmrSourceUrl": null
  },
  "trenton": {
    "areaName": "Trenton-Princeton, NJ MSA",
    "countyName": "Mercer County, NJ",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3402199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1950,
    "rent3br": 2338,
    "prior": {
      "year": 2025,
      "rent2br": 2028,
      "rent3br": 2443
    },
    "safmrSourceUrl": null
  },
  "newark": {
    "areaName": "Newark, NJ HUD Metro FMR Area",
    "countyName": "Essex County, NJ",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3401399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2205,
    "rent3br": 2761,
    "prior": {
      "year": 2025,
      "rent2br": 2140,
      "rent3br": 2695
    },
    "safmrSourceUrl": null
  },
  "paterson": {
    "areaName": "Bergen-Passaic, NJ HUD Metro FMR Area",
    "countyName": "Passaic County, NJ",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3403199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 2324,
    "rent3br": 2835,
    "prior": {
      "year": 2025,
      "rent2br": 2072,
      "rent3br": 2550
    },
    "safmrSourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3403199999&year=2026&fmrtype=Final&selection_type=county"
  },
  "reading": {
    "areaName": "Reading, PA MSA",
    "countyName": "Berks County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4201199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1575,
    "rent3br": 1937,
    "prior": {
      "year": 2025,
      "rent2br": 1353,
      "rent3br": 1689
    },
    "safmrSourceUrl": null
  },
  "lancaster": {
    "areaName": "Lancaster, PA MSA",
    "countyName": "Lancaster County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4207199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1526,
    "rent3br": 1980,
    "prior": {
      "year": 2025,
      "rent2br": 1393,
      "rent3br": 1820
    },
    "safmrSourceUrl": null
  },
  "york": {
    "areaName": "York-Hanover, PA MSA",
    "countyName": "York County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4213399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1335,
    "rent3br": 1796,
    "prior": {
      "year": 2025,
      "rent2br": 1342,
      "rent3br": 1818
    },
    "safmrSourceUrl": null
  },
  "erie": {
    "areaName": "Erie, PA MSA",
    "countyName": "Erie County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4204999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1212,
    "rent3br": 1499,
    "prior": {
      "year": 2025,
      "rent2br": 1118,
      "rent3br": 1392
    },
    "safmrSourceUrl": null
  },
  "anchorage": {
    "areaName": "Anchorage, AK HUD Metro FMR Area",
    "countyName": "Anchorage Municipality, AK",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0202099999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1631,
    "rent3br": 2268,
    "prior": {
      "year": 2025,
      "rent2br": 1563,
      "rent3br": 2190
    },
    "safmrSourceUrl": null
  },
  "philadelphia": {
    "areaName": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA",
    "countyName": "Philadelphia County, PA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4210199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1810,
    "rent3br": 2170,
    "prior": {
      "year": 2025,
      "rent2br": 1802,
      "rent3br": 2171
    },
    "safmrSourceUrl": null
  },
  "atlanta": {
    "areaName": "Atlanta-Sandy Springs-Roswell, GA HUD Metro FMR Area",
    "countyName": "Fulton County, GA",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1312199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1820,
    "rent3br": 2182,
    "prior": {
      "year": 2025,
      "rent2br": 1830,
      "rent3br": 2205
    },
    "safmrSourceUrl": null
  },
  "charlotte": {
    "areaName": "Charlotte-Concord-Gastonia, NC-SC HUD Metro FMR Area",
    "countyName": "Mecklenburg County, NC",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3711999999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1686,
    "rent3br": 2076,
    "prior": {
      "year": 2025,
      "rent2br": 1824,
      "rent3br": 2250
    },
    "safmrSourceUrl": null
  },
  "cleveland": {
    "areaName": "Cleveland, OH HUD Metro FMR Area",
    "countyName": "Cuyahoga County, OH",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=3903599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1279,
    "rent3br": 1646,
    "prior": {
      "year": 2025,
      "rent2br": 1208,
      "rent3br": 1553
    },
    "safmrSourceUrl": null
  },
  "dallas": {
    "areaName": "Dallas, TX HUD Metro FMR Area",
    "countyName": "Dallas County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4811399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1931,
    "rent3br": 2431,
    "prior": {
      "year": 2025,
      "rent2br": 1884,
      "rent3br": 2361
    },
    "safmrSourceUrl": null
  },
  "detroit": {
    "areaName": "Detroit-Warren-Livonia, MI HUD Metro FMR Area",
    "countyName": "Wayne County, MI",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2616399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1411,
    "rent3br": 1724,
    "prior": {
      "year": 2025,
      "rent2br": 1378,
      "rent3br": 1688
    },
    "safmrSourceUrl": null
  },
  "houston": {
    "areaName": "Houston-The Woodlands-Sugar Land, TX HUD Metro FMR Area",
    "countyName": "Harris County, TX",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4820199999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1573,
    "rent3br": 2116,
    "prior": {
      "year": 2025,
      "rent2br": 1529,
      "rent3br": 2038
    },
    "safmrSourceUrl": null
  },
  "indianapolis": {
    "areaName": "Indianapolis-Carmel, IN HUD Metro FMR Area",
    "countyName": "Marion County, IN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1809799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1473,
    "rent3br": 1907,
    "prior": {
      "year": 2025,
      "rent2br": 1283,
      "rent3br": 1669
    },
    "safmrSourceUrl": null
  },
  "kansas-city": {
    "areaName": "Kansas City, MO-KS HUD Metro FMR Area",
    "countyName": "Jackson County, MO",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=2909599999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1358,
    "rent3br": 1769,
    "prior": {
      "year": 2025,
      "rent2br": 1346,
      "rent3br": 1756
    },
    "safmrSourceUrl": null
  },
  "memphis": {
    "areaName": "Memphis, TN-MS-AR HUD Metro FMR Area",
    "countyName": "Shelby County, TN",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=4715799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1274,
    "rent3br": 1683,
    "prior": {
      "year": 2025,
      "rent2br": 1355,
      "rent3br": 1781
    },
    "safmrSourceUrl": null
  },
  "phoenix": {
    "areaName": "Phoenix-Mesa-Chandler, AZ MSA",
    "countyName": "Maricopa County, AZ",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=0401399999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1839,
    "rent3br": 2452,
    "prior": {
      "year": 2025,
      "rent2br": 1950,
      "rent3br": 2624
    },
    "safmrSourceUrl": null
  },
  "tampa": {
    "areaName": "Tampa-St. Petersburg-Clearwater, FL MSA",
    "countyName": "Hillsborough County, FL",
    "sourceUrl": "https://www.huduser.gov/portal/datasets/fmr/fmrs/FY2026_code/2026summary.odn?fips=1205799999&year=2026&fmrtype=Final&selection_type=county&dallas_sa_override=TRUE",
    "year": 2026,
    "rent2br": 1977,
    "rent3br": 2527,
    "prior": {
      "year": 2025,
      "rent2br": 1978,
      "rent3br": 2533
    },
    "safmrSourceUrl": null
  }
};
