/**
 * GENERATED by scripts/build-market-rents.ts — do not edit by hand.
 * Real HUD Fair Market Rent per market page (MARKET_CITIES and the bespoke
 * metros). Refresh annually, together with lib/markets/hud-fmr-areas.ts.
 *
 * Rows dated 2026-07-13 came from the HUD FMR API (git 543ea34). Rows dated
 * 2026-09-27 were copied from HUD's FY2026 FMR Documentation System, whose
 * page for each row is in lib/markets/hud-fmr-areas.ts: the 12 bespoke
 * metros (no API key was available), and worcester, lowell and manchester,
 * where the API match had used a neighbouring New England town's FMR area.
 * The script now covers both, so the next regeneration re-fetches them.
 */

export type HudRent = {
  rent2br: number;
  rent3br: number;
  /** HUD fiscal year (FY) of the figures. */
  year: number;
  /** YYYY-MM-DD the row was fetched from HUD. */
  retrievedAt: string;
};

export const HUD_RENTS: Record<string, HudRent> = {
  "columbus": {
    "rent2br": 1430,
    "rent3br": 1715,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "cincinnati": {
    "rent2br": 1353,
    "rent3br": 1785,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "pittsburgh": {
    "rent2br": 1299,
    "rent3br": 1661,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "baltimore": {
    "rent2br": 1857,
    "rent3br": 2358,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "st-louis": {
    "rent2br": 1218,
    "rent3br": 1568,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "milwaukee": {
    "rent2br": 1338,
    "rent3br": 1648,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "san-antonio": {
    "rent2br": 1426,
    "rent3br": 1830,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "jacksonville": {
    "rent2br": 1658,
    "rent3br": 2043,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "birmingham": {
    "rent2br": 1266,
    "rent3br": 1583,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "louisville": {
    "rent2br": 1272,
    "rent3br": 1625,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "nashville": {
    "rent2br": 1730,
    "rent3br": 2211,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "raleigh": {
    "rent2br": 1750,
    "rent3br": 2196,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "richmond": {
    "rent2br": 1655,
    "rent3br": 2072,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "columbia": {
    "rent2br": 1276,
    "rent3br": 1623,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "greenville": {
    "rent2br": 1339,
    "rent3br": 1612,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "oklahoma-city": {
    "rent2br": 1244,
    "rent3br": 1675,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "tulsa": {
    "rent2br": 1217,
    "rent3br": 1602,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "omaha": {
    "rent2br": 1368,
    "rent3br": 1813,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "des-moines": {
    "rent2br": 1318,
    "rent3br": 1794,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "minneapolis": {
    "rent2br": 1709,
    "rent3br": 2262,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "buffalo": {
    "rent2br": 1343,
    "rent3br": 1640,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "rochester": {
    "rent2br": 1573,
    "rent3br": 1895,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "orlando": {
    "rent2br": 1972,
    "rent3br": 2476,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "tucson": {
    "rent2br": 1402,
    "rent3br": 1950,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "grand-rapids": {
    "rent2br": 1531,
    "rent3br": 1980,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "austin": {
    "rent2br": 1852,
    "rent3br": 2347,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fort-worth": {
    "rent2br": 1723,
    "rent3br": 2273,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "denver": {
    "rent2br": 2089,
    "rent3br": 2734,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "colorado-springs": {
    "rent2br": 1735,
    "rent3br": 2413,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "salt-lake-city": {
    "rent2br": 1747,
    "rent3br": 2333,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "boise": {
    "rent2br": 1655,
    "rent3br": 2318,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "albuquerque": {
    "rent2br": 1464,
    "rent3br": 2036,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "las-vegas": {
    "rent2br": 1735,
    "rent3br": 2413,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "sacramento": {
    "rent2br": 2255,
    "rent3br": 3002,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "portland": {
    "rent2br": 1922,
    "rent3br": 2619,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "chicago": {
    "rent2br": 1781,
    "rent3br": 2294,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "madison": {
    "rent2br": 1694,
    "rent3br": 2236,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "dayton": {
    "rent2br": 1273,
    "rent3br": 1651,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "akron": {
    "rent2br": 1268,
    "rent3br": 1547,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "toledo": {
    "rent2br": 1076,
    "rent3br": 1380,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lexington": {
    "rent2br": 1272,
    "rent3br": 1743,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "knoxville": {
    "rent2br": 1471,
    "rent3br": 1864,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "chattanooga": {
    "rent2br": 1390,
    "rent3br": 1734,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "huntsville": {
    "rent2br": 1310,
    "rent3br": 1690,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "little-rock": {
    "rent2br": 1147,
    "rent3br": 1540,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "new-orleans": {
    "rent2br": 1331,
    "rent3br": 1701,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "wichita": {
    "rent2br": 1099,
    "rent3br": 1444,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "greensboro": {
    "rent2br": 1330,
    "rent3br": 1703,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "winston-salem": {
    "rent2br": 1232,
    "rent3br": 1607,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "savannah": {
    "rent2br": 1680,
    "rent3br": 2235,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fort-wayne": {
    "rent2br": 1113,
    "rent3br": 1381,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "spokane": {
    "rent2br": 1531,
    "rent3br": 2088,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "reno": {
    "rent2br": 1870,
    "rent3br": 2539,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "el-paso": {
    "rent2br": 1191,
    "rent3br": 1633,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "corpus-christi": {
    "rent2br": 1366,
    "rent3br": 1796,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "baton-rouge": {
    "rent2br": 1204,
    "rent3br": 1511,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "shreveport": {
    "rent2br": 1111,
    "rent3br": 1458,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "jackson": {
    "rent2br": 1288,
    "rent3br": 1544,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "augusta": {
    "rent2br": 1261,
    "rent3br": 1627,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "macon": {
    "rent2br": 1307,
    "rent3br": 1567,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lansing": {
    "rent2br": 1268,
    "rent3br": 1627,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fort-collins": {
    "rent2br": 1732,
    "rent3br": 2385,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "provo": {
    "rent2br": 1460,
    "rent3br": 2031,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "ogden": {
    "rent2br": 1614,
    "rent3br": 2163,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lincoln": {
    "rent2br": 1141,
    "rent3br": 1587,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "sioux-falls": {
    "rent2br": 1156,
    "rent3br": 1586,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fargo": {
    "rent2br": 1112,
    "rent3br": 1547,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "peoria": {
    "rent2br": 1039,
    "rent3br": 1346,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "rockford": {
    "rent2br": 1175,
    "rent3br": 1555,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "green-bay": {
    "rent2br": 1164,
    "rent3br": 1545,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fort-myers": {
    "rent2br": 1961,
    "rent3br": 2560,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lakeland": {
    "rent2br": 1497,
    "rent3br": 2023,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "tallahassee": {
    "rent2br": 1352,
    "rent3br": 1674,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "pensacola": {
    "rent2br": 1471,
    "rent3br": 1952,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "clarksville": {
    "rent2br": 1346,
    "rent3br": 1871,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "wilmington": {
    "rent2br": 1810,
    "rent3br": 2170,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "allentown": {
    "rent2br": 1634,
    "rent3br": 2087,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "harrisburg": {
    "rent2br": 1493,
    "rent3br": 1920,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "scranton": {
    "rent2br": 1252,
    "rent3br": 1631,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "worcester": {
    "rent2br": 2056,
    "rent3br": 2548,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "hartford": {
    "rent2br": 1865,
    "rent3br": 2236,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "new-haven": {
    "rent2br": 1969,
    "rent3br": 2433,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "providence": {
    "rent2br": 1729,
    "rent3br": 2087,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "manchester": {
    "rent2br": 2037,
    "rent3br": 2442,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "syracuse": {
    "rent2br": 1392,
    "rent3br": 1691,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "albany": {
    "rent2br": 1702,
    "rent3br": 2041,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "youngstown": {
    "rent2br": 973,
    "rent3br": 1270,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "canton": {
    "rent2br": 1086,
    "rent3br": 1371,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "evansville": {
    "rent2br": 1113,
    "rent3br": 1370,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "south-bend": {
    "rent2br": 1292,
    "rent3br": 1567,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fresno": {
    "rent2br": 1664,
    "rent3br": 2314,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "bakersfield": {
    "rent2br": 1483,
    "rent3br": 2062,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "stockton": {
    "rent2br": 1742,
    "rent3br": 2423,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "modesto": {
    "rent2br": 1758,
    "rent3br": 2442,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "salem": {
    "rent2br": 1560,
    "rent3br": 2159,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "tacoma": {
    "rent2br": 1971,
    "rent3br": 2733,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "killeen": {
    "rent2br": 1233,
    "rent3br": 1711,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "waco": {
    "rent2br": 1240,
    "rent3br": 1599,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lubbock": {
    "rent2br": 1175,
    "rent3br": 1634,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "mobile": {
    "rent2br": 1083,
    "rent3br": 1414,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "mcallen": {
    "rent2br": 1060,
    "rent3br": 1376,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "brownsville": {
    "rent2br": 1047,
    "rent3br": 1414,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "laredo": {
    "rent2br": 1161,
    "rent3br": 1499,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "amarillo": {
    "rent2br": 1106,
    "rent3br": 1503,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "beaumont": {
    "rent2br": 1103,
    "rent3br": 1446,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "denton": {
    "rent2br": 1931,
    "rent3br": 2431,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "mesa": {
    "rent2br": 1839,
    "rent3br": 2452,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "fayetteville": {
    "rent2br": 1347,
    "rent3br": 1873,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "cedar-rapids": {
    "rent2br": 1071,
    "rent3br": 1490,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "davenport": {
    "rent2br": 1143,
    "rent3br": 1498,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "topeka": {
    "rent2br": 1057,
    "rent3br": 1392,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "olathe": {
    "rent2br": 1358,
    "rent3br": 1769,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "champaign": {
    "rent2br": 1122,
    "rent3br": 1436,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "flint": {
    "rent2br": 1033,
    "rent3br": 1272,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "ann-arbor": {
    "rent2br": 1656,
    "rent3br": 1986,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "kalamazoo": {
    "rent2br": 1162,
    "rent3br": 1531,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "athens": {
    "rent2br": 1331,
    "rent3br": 1734,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "tuscaloosa": {
    "rent2br": 1169,
    "rent3br": 1490,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "montgomery": {
    "rent2br": 1016,
    "rent3br": 1304,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "gulfport": {
    "rent2br": 1140,
    "rent3br": 1471,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lafayette": {
    "rent2br": 1019,
    "rent3br": 1301,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "durham": {
    "rent2br": 1711,
    "rent3br": 2117,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "asheville": {
    "rent2br": 1835,
    "rent3br": 2231,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "norfolk": {
    "rent2br": 1713,
    "rent3br": 2376,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "virginia-beach": {
    "rent2br": 1713,
    "rent3br": 2376,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "charleston": {
    "rent2br": 1787,
    "rent3br": 2222,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "spartanburg": {
    "rent2br": 1187,
    "rent3br": 1439,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "myrtle-beach": {
    "rent2br": 1465,
    "rent3br": 1805,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "gainesville": {
    "rent2br": 1493,
    "rent3br": 1868,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "ocala": {
    "rent2br": 1373,
    "rent3br": 1772,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "daytona-beach": {
    "rent2br": 1700,
    "rent3br": 2241,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "sarasota": {
    "rent2br": 1958,
    "rent3br": 2537,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "naples": {
    "rent2br": 1986,
    "rent3br": 2581,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "boulder": {
    "rent2br": 2124,
    "rent3br": 2820,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "pueblo": {
    "rent2br": 1269,
    "rent3br": 1617,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "greeley": {
    "rent2br": 1563,
    "rent3br": 2174,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "eugene": {
    "rent2br": 1688,
    "rent3br": 2348,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "vancouver": {
    "rent2br": 1922,
    "rent3br": 2619,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "bellingham": {
    "rent2br": 1794,
    "rent3br": 2495,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "nampa": {
    "rent2br": 1655,
    "rent3br": 2318,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "billings": {
    "rent2br": 1417,
    "rent3br": 1951,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lowell": {
    "rent2br": 2351,
    "rent3br": 2819,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "trenton": {
    "rent2br": 1950,
    "rent3br": 2338,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "newark": {
    "rent2br": 2205,
    "rent3br": 2761,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "paterson": {
    "rent2br": 2324,
    "rent3br": 2835,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "reading": {
    "rent2br": 1575,
    "rent3br": 1937,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "lancaster": {
    "rent2br": 1526,
    "rent3br": 1980,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "york": {
    "rent2br": 1335,
    "rent3br": 1796,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "erie": {
    "rent2br": 1212,
    "rent3br": 1499,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "anchorage": {
    "rent2br": 1631,
    "rent3br": 2268,
    "year": 2026,
    "retrievedAt": "2026-07-13"
  },
  "philadelphia": {
    "rent2br": 1810,
    "rent3br": 2170,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "atlanta": {
    "rent2br": 1820,
    "rent3br": 2182,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "charlotte": {
    "rent2br": 1686,
    "rent3br": 2076,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "cleveland": {
    "rent2br": 1279,
    "rent3br": 1646,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "dallas": {
    "rent2br": 1931,
    "rent3br": 2431,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "detroit": {
    "rent2br": 1411,
    "rent3br": 1724,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "houston": {
    "rent2br": 1573,
    "rent3br": 2116,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "indianapolis": {
    "rent2br": 1473,
    "rent3br": 1907,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "kansas-city": {
    "rent2br": 1358,
    "rent3br": 1769,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "memphis": {
    "rent2br": 1274,
    "rent3br": 1683,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "phoenix": {
    "rent2br": 1839,
    "rent3br": 2452,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  },
  "tampa": {
    "rent2br": 1977,
    "rent3br": 2527,
    "year": 2026,
    "retrievedAt": "2026-09-27"
  }
};
