/**
 * GENERATED by scripts/build-market-rents.ts — do not edit by hand.
 * Real HUD Fair Market Rent per market city. Refresh annually.
 */

export type HudRent = {
  rent2br: number;
  rent3br: number;
  year: number;
};

export const HUD_RENTS: Record<string, HudRent> = {};
