/**
 * GENERATED by scripts/build-market-safmr.ts — do not edit by hand.
 * HUD Small Area Fair Market Rent (ZIP-level) per market city, for the
 * cities whose HUD county/metro entity publishes SAFMRs. Rows are an
 * even sample (max 12) across the rent-sorted ZIP list — every
 * figure is a real HUD number; zipCount is the entity's full ZIP count.
 * Refresh annually alongside hud-rents.ts.
 */

export type SafmrZipRent = {
  zip: string;
  rent2br: number;
  rent3br: number;
};

export type CitySafmr = {
  /** HUD entity name (county or metro FMR area). */
  areaName: string;
  /** SAFMR data year. */
  year: number;
  /** Total ZIPs in the entity (rows is a sample when larger). */
  zipCount: number;
  /** Sampled ZIP rows, sorted by 2BR rent descending. */
  rows: SafmrZipRent[];
};

export const SAFMR_RENTS: Record<string, CitySafmr> = {
  "columbus": {
    "areaName": "Columbus, OH metro area",
    "year": 2026,
    "zipCount": 142,
    "rows": [
      {
        "zip": "43215",
        "rent2br": 2150,
        "rent3br": 2580
      },
      {
        "zip": "43230",
        "rent2br": 1700,
        "rent3br": 2040
      },
      {
        "zip": "43021",
        "rent2br": 1520,
        "rent3br": 1820
      },
      {
        "zip": "43040",
        "rent2br": 1430,
        "rent3br": 1710
      },
      {
        "zip": "43350",
        "rent2br": 1380,
        "rent3br": 1650
      },
      {
        "zip": "43204",
        "rent2br": 1300,
        "rent3br": 1560
      },
      {
        "zip": "43112",
        "rent2br": 1240,
        "rent3br": 1490
      },
      {
        "zip": "43320",
        "rent2br": 1190,
        "rent3br": 1440
      },
      {
        "zip": "43740",
        "rent2br": 1150,
        "rent3br": 1450
      },
      {
        "zip": "43321",
        "rent2br": 1100,
        "rent3br": 1320
      },
      {
        "zip": "43105",
        "rent2br": 1070,
        "rent3br": 1280
      },
      {
        "zip": "45644",
        "rent2br": 1070,
        "rent3br": 1280
      }
    ]
  },
  "cincinnati": {
    "areaName": "Cincinnati, OH-KY-IN metro area",
    "year": 2026,
    "zipCount": 184,
    "rows": [
      {
        "zip": "41091",
        "rent2br": 2030,
        "rent3br": 2680
      },
      {
        "zip": "45067",
        "rent2br": 1710,
        "rent3br": 2260
      },
      {
        "zip": "45162",
        "rent2br": 1540,
        "rent3br": 2030
      },
      {
        "zip": "45018",
        "rent2br": 1400,
        "rent3br": 1850
      },
      {
        "zip": "45236",
        "rent2br": 1360,
        "rent3br": 1790
      },
      {
        "zip": "45201",
        "rent2br": 1310,
        "rent3br": 1730
      },
      {
        "zip": "45053",
        "rent2br": 1280,
        "rent3br": 1690
      },
      {
        "zip": "45113",
        "rent2br": 1210,
        "rent3br": 1590
      },
      {
        "zip": "45217",
        "rent2br": 1170,
        "rent3br": 1540
      },
      {
        "zip": "41043",
        "rent2br": 1100,
        "rent3br": 1450
      },
      {
        "zip": "47017",
        "rent2br": 1020,
        "rent3br": 1310
      },
      {
        "zip": "47038",
        "rent2br": 980,
        "rent3br": 1300
      }
    ]
  },
  "pittsburgh": {
    "areaName": "Pittsburgh, PA metro area",
    "year": 2026,
    "zipCount": 393,
    "rows": [
      {
        "zip": "15015",
        "rent2br": 1950,
        "rent3br": 2490
      },
      {
        "zip": "15086",
        "rent2br": 1480,
        "rent3br": 1890
      },
      {
        "zip": "15262",
        "rent2br": 1390,
        "rent3br": 1780
      },
      {
        "zip": "15637",
        "rent2br": 1320,
        "rent3br": 1690
      },
      {
        "zip": "15420",
        "rent2br": 1220,
        "rent3br": 1560
      },
      {
        "zip": "15464",
        "rent2br": 1180,
        "rent3br": 1510
      },
      {
        "zip": "15358",
        "rent2br": 1140,
        "rent3br": 1460
      },
      {
        "zip": "15606",
        "rent2br": 1110,
        "rent3br": 1420
      },
      {
        "zip": "16115",
        "rent2br": 1080,
        "rent3br": 1380
      },
      {
        "zip": "15415",
        "rent2br": 1020,
        "rent3br": 1300
      },
      {
        "zip": "15429",
        "rent2br": 980,
        "rent3br": 1250
      },
      {
        "zip": "16373",
        "rent2br": 970,
        "rent3br": 1220
      }
    ]
  },
  "st-louis": {
    "areaName": "St. Louis, MO-IL metro area",
    "year": 2026,
    "zipCount": 268,
    "rows": [
      {
        "zip": "62225",
        "rent2br": 1830,
        "rent3br": 2360
      },
      {
        "zip": "63101",
        "rent2br": 1460,
        "rent3br": 1880
      },
      {
        "zip": "63104",
        "rent2br": 1330,
        "rent3br": 1710
      },
      {
        "zip": "62355",
        "rent2br": 1260,
        "rent3br": 1560
      },
      {
        "zip": "62202",
        "rent2br": 1190,
        "rent3br": 1530
      },
      {
        "zip": "63343",
        "rent2br": 1150,
        "rent3br": 1480
      },
      {
        "zip": "63065",
        "rent2br": 1100,
        "rent3br": 1420
      },
      {
        "zip": "62239",
        "rent2br": 1060,
        "rent3br": 1360
      },
      {
        "zip": "63020",
        "rent2br": 1010,
        "rent3br": 1300
      },
      {
        "zip": "62074",
        "rent2br": 990,
        "rent3br": 1270
      },
      {
        "zip": "63056",
        "rent2br": 990,
        "rent3br": 1270
      },
      {
        "zip": "65453",
        "rent2br": 990,
        "rent3br": 1270
      }
    ]
  },
  "san-antonio": {
    "areaName": "San Antonio-New Braunfels, TX metro area",
    "year": 2026,
    "zipCount": 138,
    "rows": [
      {
        "zip": "78108",
        "rent2br": 2140,
        "rent3br": 2750
      },
      {
        "zip": "78257",
        "rent2br": 1840,
        "rent3br": 2360
      },
      {
        "zip": "78259",
        "rent2br": 1650,
        "rent3br": 2120
      },
      {
        "zip": "78204",
        "rent2br": 1570,
        "rent3br": 2010
      },
      {
        "zip": "78070",
        "rent2br": 1440,
        "rent3br": 1830
      },
      {
        "zip": "78269",
        "rent2br": 1410,
        "rent3br": 1810
      },
      {
        "zip": "78295",
        "rent2br": 1410,
        "rent3br": 1810
      },
      {
        "zip": "78112",
        "rent2br": 1350,
        "rent3br": 1730
      },
      {
        "zip": "78147",
        "rent2br": 1290,
        "rent3br": 1660
      },
      {
        "zip": "78219",
        "rent2br": 1230,
        "rent3br": 1580
      },
      {
        "zip": "78028",
        "rent2br": 1130,
        "rent3br": 1490
      },
      {
        "zip": "78101",
        "rent2br": 970,
        "rent3br": 1250
      }
    ]
  },
  "jacksonville": {
    "areaName": "Jacksonville, FL metro area",
    "year": 2026,
    "zipCount": 82,
    "rows": [
      {
        "zip": "32226",
        "rent2br": 2490,
        "rent3br": 3070
      },
      {
        "zip": "32228",
        "rent2br": 2270,
        "rent3br": 2840
      },
      {
        "zip": "32260",
        "rent2br": 2030,
        "rent3br": 2500
      },
      {
        "zip": "32225",
        "rent2br": 1930,
        "rent3br": 2380
      },
      {
        "zip": "32006",
        "rent2br": 1720,
        "rent3br": 2120
      },
      {
        "zip": "32084",
        "rent2br": 1650,
        "rent3br": 2030
      },
      {
        "zip": "32236",
        "rent2br": 1630,
        "rent3br": 2010
      },
      {
        "zip": "32257",
        "rent2br": 1620,
        "rent3br": 2000
      },
      {
        "zip": "32207",
        "rent2br": 1500,
        "rent3br": 1850
      },
      {
        "zip": "32140",
        "rent2br": 1380,
        "rent3br": 1730
      },
      {
        "zip": "32209",
        "rent2br": 1200,
        "rent3br": 1480
      },
      {
        "zip": "32091",
        "rent2br": 1080,
        "rent3br": 1380
      }
    ]
  },
  "birmingham": {
    "areaName": "Birmingham-Hoover, AL metro area",
    "year": 2026,
    "zipCount": 133,
    "rows": [
      {
        "zip": "35213",
        "rent2br": 1900,
        "rent3br": 2380
      },
      {
        "zip": "35209",
        "rent2br": 1580,
        "rent3br": 1980
      },
      {
        "zip": "35061",
        "rent2br": 1370,
        "rent3br": 1710
      },
      {
        "zip": "35201",
        "rent2br": 1260,
        "rent3br": 1580
      },
      {
        "zip": "35261",
        "rent2br": 1260,
        "rent3br": 1580
      },
      {
        "zip": "35064",
        "rent2br": 1200,
        "rent3br": 1500
      },
      {
        "zip": "35036",
        "rent2br": 1120,
        "rent3br": 1400
      },
      {
        "zip": "35074",
        "rent2br": 1070,
        "rent3br": 1340
      },
      {
        "zip": "35013",
        "rent2br": 1020,
        "rent3br": 1280
      },
      {
        "zip": "35079",
        "rent2br": 1020,
        "rent3br": 1280
      },
      {
        "zip": "35180",
        "rent2br": 1020,
        "rent3br": 1280
      },
      {
        "zip": "35980",
        "rent2br": 1020,
        "rent3br": 1280
      }
    ]
  },
  "louisville": {
    "areaName": "Louisville, KY-IN metro area",
    "year": 2026,
    "zipCount": 130,
    "rows": [
      {
        "zip": "40059",
        "rent2br": 1910,
        "rent3br": 2440
      },
      {
        "zip": "40229",
        "rent2br": 1490,
        "rent3br": 1900
      },
      {
        "zip": "40280",
        "rent2br": 1400,
        "rent3br": 1790
      },
      {
        "zip": "40057",
        "rent2br": 1330,
        "rent3br": 1690
      },
      {
        "zip": "40232",
        "rent2br": 1290,
        "rent3br": 1650
      },
      {
        "zip": "40268",
        "rent2br": 1290,
        "rent3br": 1650
      },
      {
        "zip": "40215",
        "rent2br": 1220,
        "rent3br": 1560
      },
      {
        "zip": "40165",
        "rent2br": 1160,
        "rent3br": 1480
      },
      {
        "zip": "40211",
        "rent2br": 1110,
        "rent3br": 1420
      },
      {
        "zip": "40216",
        "rent2br": 1080,
        "rent3br": 1390
      },
      {
        "zip": "40177",
        "rent2br": 1070,
        "rent3br": 1390
      },
      {
        "zip": "47243",
        "rent2br": 1070,
        "rent3br": 1390
      }
    ]
  },
  "nashville": {
    "areaName": "Nashville-Davidson--Murfreesboro--Franklin, TN metro area",
    "year": 2026,
    "zipCount": 125,
    "rows": [
      {
        "zip": "37069",
        "rent2br": 2600,
        "rent3br": 3320
      },
      {
        "zip": "37067",
        "rent2br": 2250,
        "rent3br": 2880
      },
      {
        "zip": "37153",
        "rent2br": 1920,
        "rent3br": 2450
      },
      {
        "zip": "37076",
        "rent2br": 1780,
        "rent3br": 2280
      },
      {
        "zip": "37232",
        "rent2br": 1770,
        "rent3br": 2260
      },
      {
        "zip": "37133",
        "rent2br": 1660,
        "rent3br": 2120
      },
      {
        "zip": "37210",
        "rent2br": 1580,
        "rent3br": 2020
      },
      {
        "zip": "37015",
        "rent2br": 1460,
        "rent3br": 1870
      },
      {
        "zip": "37012",
        "rent2br": 1320,
        "rent3br": 1660
      },
      {
        "zip": "37052",
        "rent2br": 1320,
        "rent3br": 1660
      },
      {
        "zip": "37165",
        "rent2br": 1320,
        "rent3br": 1660
      },
      {
        "zip": "37110",
        "rent2br": 970,
        "rent3br": 1170
      }
    ]
  },
  "raleigh": {
    "areaName": "Raleigh-Cary, NC metro area",
    "year": 2026,
    "zipCount": 86,
    "rows": [
      {
        "zip": "27519",
        "rent2br": 2240,
        "rent3br": 2810
      },
      {
        "zip": "27617",
        "rent2br": 2010,
        "rent3br": 2520
      },
      {
        "zip": "27614",
        "rent2br": 1860,
        "rent3br": 2330
      },
      {
        "zip": "27611",
        "rent2br": 1810,
        "rent3br": 2270
      },
      {
        "zip": "27629",
        "rent2br": 1810,
        "rent3br": 2270
      },
      {
        "zip": "27690",
        "rent2br": 1810,
        "rent3br": 2270
      },
      {
        "zip": "27571",
        "rent2br": 1750,
        "rent3br": 2210
      },
      {
        "zip": "27520",
        "rent2br": 1630,
        "rent3br": 2050
      },
      {
        "zip": "27508",
        "rent2br": 1350,
        "rent3br": 1660
      },
      {
        "zip": "27555",
        "rent2br": 1350,
        "rent3br": 1660
      },
      {
        "zip": "27592",
        "rent2br": 1350,
        "rent3br": 1660
      },
      {
        "zip": "28366",
        "rent2br": 1350,
        "rent3br": 1660
      }
    ]
  },
  "oklahoma-city": {
    "areaName": "Oklahoma City, OK metro area",
    "year": 2026,
    "zipCount": 129,
    "rows": [
      {
        "zip": "73012",
        "rent2br": 1870,
        "rent3br": 2520
      },
      {
        "zip": "73102",
        "rent2br": 1510,
        "rent3br": 2030
      },
      {
        "zip": "73034",
        "rent2br": 1370,
        "rent3br": 1840
      },
      {
        "zip": "73162",
        "rent2br": 1300,
        "rent3br": 1750
      },
      {
        "zip": "73008",
        "rent2br": 1220,
        "rent3br": 1640
      },
      {
        "zip": "73147",
        "rent2br": 1220,
        "rent3br": 1640
      },
      {
        "zip": "73195",
        "rent2br": 1220,
        "rent3br": 1640
      },
      {
        "zip": "73132",
        "rent2br": 1150,
        "rent3br": 1550
      },
      {
        "zip": "73121",
        "rent2br": 1080,
        "rent3br": 1450
      },
      {
        "zip": "73052",
        "rent2br": 1030,
        "rent3br": 1370
      },
      {
        "zip": "74831",
        "rent2br": 990,
        "rent3br": 1320
      },
      {
        "zip": "74881",
        "rent2br": 940,
        "rent3br": 1260
      }
    ]
  },
  "tulsa": {
    "areaName": "Tulsa, OK metro area",
    "year": 2026,
    "zipCount": 122,
    "rows": [
      {
        "zip": "74037",
        "rent2br": 1720,
        "rent3br": 2260
      },
      {
        "zip": "74021",
        "rent2br": 1390,
        "rent3br": 1830
      },
      {
        "zip": "74015",
        "rent2br": 1260,
        "rent3br": 1660
      },
      {
        "zip": "74149",
        "rent2br": 1230,
        "rent3br": 1620
      },
      {
        "zip": "74172",
        "rent2br": 1230,
        "rent3br": 1620
      },
      {
        "zip": "74117",
        "rent2br": 1190,
        "rent3br": 1570
      },
      {
        "zip": "74001",
        "rent2br": 1110,
        "rent3br": 1460
      },
      {
        "zip": "74129",
        "rent2br": 1080,
        "rent3br": 1420
      },
      {
        "zip": "74436",
        "rent2br": 1000,
        "rent3br": 1270
      },
      {
        "zip": "74016",
        "rent2br": 940,
        "rent3br": 1230
      },
      {
        "zip": "74056",
        "rent2br": 940,
        "rent3br": 1230
      },
      {
        "zip": "74637",
        "rent2br": 940,
        "rent3br": 1230
      }
    ]
  },
  "omaha": {
    "areaName": "Omaha-Council Bluffs, NE-IA metro area",
    "year": 2026,
    "zipCount": 133,
    "rows": [
      {
        "zip": "68118",
        "rent2br": 2050,
        "rent3br": 2720
      },
      {
        "zip": "68068",
        "rent2br": 1610,
        "rent3br": 2130
      },
      {
        "zip": "68128",
        "rent2br": 1470,
        "rent3br": 1950
      },
      {
        "zip": "68145",
        "rent2br": 1370,
        "rent3br": 1820
      },
      {
        "zip": "51561",
        "rent2br": 1320,
        "rent3br": 1750
      },
      {
        "zip": "68005",
        "rent2br": 1240,
        "rent3br": 1640
      },
      {
        "zip": "68029",
        "rent2br": 1180,
        "rent3br": 1560
      },
      {
        "zip": "68178",
        "rent2br": 1150,
        "rent3br": 1520
      },
      {
        "zip": "68403",
        "rent2br": 1080,
        "rent3br": 1430
      },
      {
        "zip": "51555",
        "rent2br": 1040,
        "rent3br": 1380
      },
      {
        "zip": "51577",
        "rent2br": 970,
        "rent3br": 1280
      },
      {
        "zip": "68347",
        "rent2br": 960,
        "rent3br": 1280
      }
    ]
  },
  "des-moines": {
    "areaName": "Des Moines-West Des Moines, IA metro area",
    "year": 2026,
    "zipCount": 111,
    "rows": [
      {
        "zip": "50021",
        "rent2br": 1680,
        "rent3br": 2290
      },
      {
        "zip": "50023",
        "rent2br": 1440,
        "rent3br": 1960
      },
      {
        "zip": "50322",
        "rent2br": 1330,
        "rent3br": 1810
      },
      {
        "zip": "50319",
        "rent2br": 1300,
        "rent3br": 1770
      },
      {
        "zip": "50243",
        "rent2br": 1280,
        "rent3br": 1760
      },
      {
        "zip": "50315",
        "rent2br": 1230,
        "rent3br": 1670
      },
      {
        "zip": "50125",
        "rent2br": 1150,
        "rent3br": 1570
      },
      {
        "zip": "50166",
        "rent2br": 1090,
        "rent3br": 1480
      },
      {
        "zip": "50250",
        "rent2br": 1040,
        "rent3br": 1390
      },
      {
        "zip": "50029",
        "rent2br": 1000,
        "rent3br": 1360
      },
      {
        "zip": "50225",
        "rent2br": 960,
        "rent3br": 1200
      },
      {
        "zip": "50858",
        "rent2br": 920,
        "rent3br": 1200
      }
    ]
  },
  "buffalo": {
    "areaName": "Buffalo-Cheektowaga, NY metro area",
    "year": 2026,
    "zipCount": 114,
    "rows": [
      {
        "zip": "14026",
        "rent2br": 2010,
        "rent3br": 2450
      },
      {
        "zip": "14228",
        "rent2br": 1700,
        "rent3br": 2080
      },
      {
        "zip": "14174",
        "rent2br": 1440,
        "rent3br": 1760
      },
      {
        "zip": "14151",
        "rent2br": 1380,
        "rent3br": 1690
      },
      {
        "zip": "14201",
        "rent2br": 1360,
        "rent3br": 1660
      },
      {
        "zip": "14217",
        "rent2br": 1310,
        "rent3br": 1600
      },
      {
        "zip": "14052",
        "rent2br": 1260,
        "rent3br": 1540
      },
      {
        "zip": "14031",
        "rent2br": 1220,
        "rent3br": 1490
      },
      {
        "zip": "14107",
        "rent2br": 1180,
        "rent3br": 1440
      },
      {
        "zip": "14207",
        "rent2br": 1160,
        "rent3br": 1420
      },
      {
        "zip": "14105",
        "rent2br": 1070,
        "rent3br": 1290
      },
      {
        "zip": "14145",
        "rent2br": 970,
        "rent3br": 1330
      }
    ]
  },
  "orlando": {
    "areaName": "Orlando-Kissimmee-Sanford, FL metro area",
    "year": 2026,
    "zipCount": 154,
    "rows": [
      {
        "zip": "34773",
        "rent2br": 2760,
        "rent3br": 3460
      },
      {
        "zip": "32803",
        "rent2br": 2350,
        "rent3br": 2950
      },
      {
        "zip": "34747",
        "rent2br": 2220,
        "rent3br": 2790
      },
      {
        "zip": "32817",
        "rent2br": 2070,
        "rent3br": 2600
      },
      {
        "zip": "32719",
        "rent2br": 2000,
        "rent3br": 2510
      },
      {
        "zip": "32853",
        "rent2br": 2000,
        "rent3br": 2510
      },
      {
        "zip": "32872",
        "rent2br": 2000,
        "rent3br": 2510
      },
      {
        "zip": "34741",
        "rent2br": 1950,
        "rent3br": 2450
      },
      {
        "zip": "32812",
        "rent2br": 1820,
        "rent3br": 2280
      },
      {
        "zip": "34749",
        "rent2br": 1720,
        "rent3br": 2160
      },
      {
        "zip": "32195",
        "rent2br": 1520,
        "rent3br": 1920
      },
      {
        "zip": "33898",
        "rent2br": 1330,
        "rent3br": 1800
      }
    ]
  },
  "tucson": {
    "areaName": "Tucson, AZ metro area",
    "year": 2026,
    "zipCount": 70,
    "rows": [
      {
        "zip": "85641",
        "rent2br": 2100,
        "rent3br": 2920
      },
      {
        "zip": "85739",
        "rent2br": 2030,
        "rent3br": 2760
      },
      {
        "zip": "85756",
        "rent2br": 1730,
        "rent3br": 2410
      },
      {
        "zip": "85654",
        "rent2br": 1620,
        "rent3br": 2250
      },
      {
        "zip": "85701",
        "rent2br": 1540,
        "rent3br": 2140
      },
      {
        "zip": "85611",
        "rent2br": 1500,
        "rent3br": 2080
      },
      {
        "zip": "85652",
        "rent2br": 1400,
        "rent3br": 1950
      },
      {
        "zip": "85724",
        "rent2br": 1400,
        "rent3br": 1950
      },
      {
        "zip": "85733",
        "rent2br": 1400,
        "rent3br": 1950
      },
      {
        "zip": "85719",
        "rent2br": 1380,
        "rent3br": 1920
      },
      {
        "zip": "85639",
        "rent2br": 1230,
        "rent3br": 1720
      },
      {
        "zip": "85714",
        "rent2br": 1090,
        "rent3br": 1530
      }
    ]
  },
  "fort-worth": {
    "areaName": "Fort Worth-Arlington, TX metro area",
    "year": 2026,
    "zipCount": 126,
    "rows": [
      {
        "zip": "75028",
        "rent2br": 2800,
        "rent3br": 3520
      },
      {
        "zip": "76244",
        "rent2br": 2340,
        "rent3br": 3090
      },
      {
        "zip": "76177",
        "rent2br": 2120,
        "rent3br": 2770
      },
      {
        "zip": "76126",
        "rent2br": 1960,
        "rent3br": 2590
      },
      {
        "zip": "76107",
        "rent2br": 1820,
        "rent3br": 2400
      },
      {
        "zip": "76095",
        "rent2br": 1730,
        "rent3br": 2280
      },
      {
        "zip": "76161",
        "rent2br": 1730,
        "rent3br": 2280
      },
      {
        "zip": "76058",
        "rent2br": 1660,
        "rent3br": 2190
      },
      {
        "zip": "76049",
        "rent2br": 1600,
        "rent3br": 1930
      },
      {
        "zip": "76116",
        "rent2br": 1520,
        "rent3br": 2010
      },
      {
        "zip": "76119",
        "rent2br": 1400,
        "rent3br": 1850
      },
      {
        "zip": "76486",
        "rent2br": 970,
        "rent3br": 1320
      }
    ]
  },
  "colorado-springs": {
    "areaName": "Colorado Springs, CO metro area",
    "year": 2026,
    "zipCount": 62,
    "rows": [
      {
        "zip": "80927",
        "rent2br": 2600,
        "rent3br": 3620
      },
      {
        "zip": "80132",
        "rent2br": 2320,
        "rent3br": 3230
      },
      {
        "zip": "80902",
        "rent2br": 2200,
        "rent3br": 3060
      },
      {
        "zip": "80913",
        "rent2br": 2080,
        "rent3br": 2890
      },
      {
        "zip": "80906",
        "rent2br": 1880,
        "rent3br": 2610
      },
      {
        "zip": "80901",
        "rent2br": 1740,
        "rent3br": 2420
      },
      {
        "zip": "80934",
        "rent2br": 1740,
        "rent3br": 2420
      },
      {
        "zip": "80960",
        "rent2br": 1740,
        "rent3br": 2420
      },
      {
        "zip": "81008",
        "rent2br": 1650,
        "rent3br": 2100
      },
      {
        "zip": "80917",
        "rent2br": 1550,
        "rent3br": 2160
      },
      {
        "zip": "80835",
        "rent2br": 1440,
        "rent3br": 1890
      },
      {
        "zip": "80833",
        "rent2br": 1120,
        "rent3br": 1460
      }
    ]
  },
  "sacramento": {
    "areaName": "Sacramento--Roseville--Arden-Arcade, CA metro area",
    "year": 2026,
    "zipCount": 130,
    "rows": [
      {
        "zip": "95742",
        "rent2br": 3380,
        "rent3br": 4500
      },
      {
        "zip": "95835",
        "rent2br": 2840,
        "rent3br": 3780
      },
      {
        "zip": "95819",
        "rent2br": 2640,
        "rent3br": 3510
      },
      {
        "zip": "95833",
        "rent2br": 2480,
        "rent3br": 3300
      },
      {
        "zip": "95864",
        "rent2br": 2370,
        "rent3br": 3150
      },
      {
        "zip": "95611",
        "rent2br": 2220,
        "rent3br": 2960
      },
      {
        "zip": "95866",
        "rent2br": 2220,
        "rent3br": 2960
      },
      {
        "zip": "95651",
        "rent2br": 2160,
        "rent3br": 2880
      },
      {
        "zip": "95842",
        "rent2br": 2070,
        "rent3br": 2760
      },
      {
        "zip": "95680",
        "rent2br": 1950,
        "rent3br": 2640
      },
      {
        "zip": "95629",
        "rent2br": 1770,
        "rent3br": 2340
      },
      {
        "zip": "95615",
        "rent2br": 1350,
        "rent3br": 1800
      }
    ]
  },
  "chicago": {
    "areaName": "Chicago-Joliet-Naperville, IL metro area",
    "year": 2026,
    "zipCount": 370,
    "rows": [
      {
        "zip": "60010",
        "rent2br": 2670,
        "rent3br": 3440
      },
      {
        "zip": "60089",
        "rent2br": 2560,
        "rent3br": 3300
      },
      {
        "zip": "60640",
        "rent2br": 2300,
        "rent3br": 2960
      },
      {
        "zip": "60410",
        "rent2br": 2100,
        "rent3br": 2750
      },
      {
        "zip": "60443",
        "rent2br": 2000,
        "rent3br": 2580
      },
      {
        "zip": "60484",
        "rent2br": 1840,
        "rent3br": 2370
      },
      {
        "zip": "60121",
        "rent2br": 1750,
        "rent3br": 2250
      },
      {
        "zip": "60701",
        "rent2br": 1750,
        "rent3br": 2250
      },
      {
        "zip": "60510",
        "rent2br": 1620,
        "rent3br": 2090
      },
      {
        "zip": "60649",
        "rent2br": 1520,
        "rent3br": 1960
      },
      {
        "zip": "60155",
        "rent2br": 1420,
        "rent3br": 1830
      },
      {
        "zip": "61012",
        "rent2br": 1170,
        "rent3br": 1550
      }
    ]
  },
  "dayton": {
    "areaName": "Dayton-Kettering-Beavercreek, OH metro area",
    "year": 2026,
    "zipCount": 88,
    "rows": [
      {
        "zip": "45066",
        "rent2br": 1970,
        "rent3br": 2590
      },
      {
        "zip": "45431",
        "rent2br": 1600,
        "rent3br": 2080
      },
      {
        "zip": "45371",
        "rent2br": 1410,
        "rent3br": 1830
      },
      {
        "zip": "45324",
        "rent2br": 1330,
        "rent3br": 1720
      },
      {
        "zip": "45439",
        "rent2br": 1260,
        "rent3br": 1630
      },
      {
        "zip": "45441",
        "rent2br": 1250,
        "rent3br": 1620
      },
      {
        "zip": "45356",
        "rent2br": 1220,
        "rent3br": 1580
      },
      {
        "zip": "45415",
        "rent2br": 1190,
        "rent3br": 1540
      },
      {
        "zip": "45378",
        "rent2br": 1150,
        "rent3br": 1530
      },
      {
        "zip": "45307",
        "rent2br": 1070,
        "rent3br": 1390
      },
      {
        "zip": "45381",
        "rent2br": 1010,
        "rent3br": 1340
      },
      {
        "zip": "45368",
        "rent2br": 970,
        "rent3br": 1190
      }
    ]
  },
  "akron": {
    "areaName": "Akron, OH metro area",
    "year": 2026,
    "zipCount": 71,
    "rows": [
      {
        "zip": "44056",
        "rent2br": 1900,
        "rent3br": 2320
      },
      {
        "zip": "44087",
        "rent2br": 1600,
        "rent3br": 1950
      },
      {
        "zip": "44221",
        "rent2br": 1380,
        "rent3br": 1680
      },
      {
        "zip": "44211",
        "rent2br": 1300,
        "rent3br": 1590
      },
      {
        "zip": "44240",
        "rent2br": 1280,
        "rent3br": 1560
      },
      {
        "zip": "44210",
        "rent2br": 1260,
        "rent3br": 1540
      },
      {
        "zip": "44334",
        "rent2br": 1260,
        "rent3br": 1540
      },
      {
        "zip": "44304",
        "rent2br": 1200,
        "rent3br": 1460
      },
      {
        "zip": "44320",
        "rent2br": 1150,
        "rent3br": 1400
      },
      {
        "zip": "44308",
        "rent2br": 1120,
        "rent3br": 1360
      },
      {
        "zip": "44412",
        "rent2br": 1020,
        "rent3br": 1260
      },
      {
        "zip": "44470",
        "rent2br": 970,
        "rent3br": 1270
      }
    ]
  },
  "knoxville": {
    "areaName": "Knoxville, TN metro area",
    "year": 2026,
    "zipCount": 73,
    "rows": [
      {
        "zip": "37934",
        "rent2br": 2210,
        "rent3br": 2800
      },
      {
        "zip": "37705",
        "rent2br": 1680,
        "rent3br": 2130
      },
      {
        "zip": "37928",
        "rent2br": 1530,
        "rent3br": 1940
      },
      {
        "zip": "37995",
        "rent2br": 1530,
        "rent3br": 1940
      },
      {
        "zip": "37804",
        "rent2br": 1470,
        "rent3br": 1860
      },
      {
        "zip": "37721",
        "rent2br": 1380,
        "rent3br": 1780
      },
      {
        "zip": "37886",
        "rent2br": 1340,
        "rent3br": 1700
      },
      {
        "zip": "37882",
        "rent2br": 1310,
        "rent3br": 1660
      },
      {
        "zip": "37742",
        "rent2br": 1240,
        "rent3br": 1570
      },
      {
        "zip": "37777",
        "rent2br": 1080,
        "rent3br": 1380
      },
      {
        "zip": "37846",
        "rent2br": 1040,
        "rent3br": 1340
      },
      {
        "zip": "37874",
        "rent2br": 990,
        "rent3br": 1290
      }
    ]
  },
  "chattanooga": {
    "areaName": "Chattanooga, TN-GA metro area",
    "year": 2026,
    "zipCount": 71,
    "rows": [
      {
        "zip": "37350",
        "rent2br": 1900,
        "rent3br": 2370
      },
      {
        "zip": "37403",
        "rent2br": 1650,
        "rent3br": 2060
      },
      {
        "zip": "37351",
        "rent2br": 1480,
        "rent3br": 1850
      },
      {
        "zip": "37450",
        "rent2br": 1480,
        "rent3br": 1850
      },
      {
        "zip": "30739",
        "rent2br": 1350,
        "rent3br": 1700
      },
      {
        "zip": "30726",
        "rent2br": 1260,
        "rent3br": 1570
      },
      {
        "zip": "37311",
        "rent2br": 1220,
        "rent3br": 1570
      },
      {
        "zip": "37407",
        "rent2br": 1180,
        "rent3br": 1470
      },
      {
        "zip": "30725",
        "rent2br": 1100,
        "rent3br": 1390
      },
      {
        "zip": "30740",
        "rent2br": 1070,
        "rent3br": 1390
      },
      {
        "zip": "30747",
        "rent2br": 970,
        "rent3br": 1350
      },
      {
        "zip": "38585",
        "rent2br": 970,
        "rent3br": 1260
      }
    ]
  },
  "wichita": {
    "areaName": "Wichita, KS metro area",
    "year": 2026,
    "zipCount": 83,
    "rows": [
      {
        "zip": "67002",
        "rent2br": 1650,
        "rent3br": 2170
      },
      {
        "zip": "67223",
        "rent2br": 1550,
        "rent3br": 2040
      },
      {
        "zip": "67017",
        "rent2br": 1340,
        "rent3br": 1760
      },
      {
        "zip": "67037",
        "rent2br": 1230,
        "rent3br": 1620
      },
      {
        "zip": "67001",
        "rent2br": 1130,
        "rent3br": 1480
      },
      {
        "zip": "67201",
        "rent2br": 1100,
        "rent3br": 1450
      },
      {
        "zip": "67260",
        "rent2br": 1090,
        "rent3br": 1430
      },
      {
        "zip": "67056",
        "rent2br": 1050,
        "rent3br": 1380
      },
      {
        "zip": "67042",
        "rent2br": 1000,
        "rent3br": 1310
      },
      {
        "zip": "67546",
        "rent2br": 960,
        "rent3br": 1230
      },
      {
        "zip": "67543",
        "rent2br": 890,
        "rent3br": 1090
      },
      {
        "zip": "67522",
        "rent2br": 880,
        "rent3br": 1090
      }
    ]
  },
  "greensboro": {
    "areaName": "Greensboro-High Point, NC metro area",
    "year": 2026,
    "zipCount": 69,
    "rows": [
      {
        "zip": "27301",
        "rent2br": 2000,
        "rent3br": 2560
      },
      {
        "zip": "27455",
        "rent2br": 1500,
        "rent3br": 1920
      },
      {
        "zip": "27214",
        "rent2br": 1410,
        "rent3br": 1800
      },
      {
        "zip": "27406",
        "rent2br": 1370,
        "rent3br": 1750
      },
      {
        "zip": "27420",
        "rent2br": 1370,
        "rent3br": 1750
      },
      {
        "zip": "27498",
        "rent2br": 1370,
        "rent3br": 1750
      },
      {
        "zip": "27325",
        "rent2br": 1330,
        "rent3br": 1670
      },
      {
        "zip": "27233",
        "rent2br": 1260,
        "rent3br": 1610
      },
      {
        "zip": "27260",
        "rent2br": 1180,
        "rent3br": 1510
      },
      {
        "zip": "27313",
        "rent2br": 1110,
        "rent3br": 1420
      },
      {
        "zip": "27317",
        "rent2br": 1050,
        "rent3br": 1340
      },
      {
        "zip": "27371",
        "rent2br": 960,
        "rent3br": 1250
      }
    ]
  },
  "winston-salem": {
    "areaName": "Winston-Salem, NC metro area",
    "year": 2026,
    "zipCount": 62,
    "rows": [
      {
        "zip": "27235",
        "rent2br": 1900,
        "rent3br": 2430
      },
      {
        "zip": "27103",
        "rent2br": 1380,
        "rent3br": 1800
      },
      {
        "zip": "27016",
        "rent2br": 1310,
        "rent3br": 1710
      },
      {
        "zip": "27102",
        "rent2br": 1270,
        "rent3br": 1660
      },
      {
        "zip": "27115",
        "rent2br": 1270,
        "rent3br": 1660
      },
      {
        "zip": "27150",
        "rent2br": 1270,
        "rent3br": 1660
      },
      {
        "zip": "27285",
        "rent2br": 1270,
        "rent3br": 1660
      },
      {
        "zip": "28625",
        "rent2br": 1110,
        "rent3br": 1500
      },
      {
        "zip": "27050",
        "rent2br": 1050,
        "rent3br": 1370
      },
      {
        "zip": "27055",
        "rent2br": 990,
        "rent3br": 1350
      },
      {
        "zip": "27041",
        "rent2br": 940,
        "rent3br": 1180
      },
      {
        "zip": "28642",
        "rent2br": 930,
        "rent3br": 1210
      }
    ]
  },
  "fort-wayne": {
    "areaName": "Fort Wayne, IN metro area",
    "year": 2026,
    "zipCount": 63,
    "rows": [
      {
        "zip": "46748",
        "rent2br": 1670,
        "rent3br": 2070
      },
      {
        "zip": "46765",
        "rent2br": 1360,
        "rent3br": 1690
      },
      {
        "zip": "46788",
        "rent2br": 1180,
        "rent3br": 1470
      },
      {
        "zip": "46852",
        "rent2br": 1120,
        "rent3br": 1390
      },
      {
        "zip": "46858",
        "rent2br": 1120,
        "rent3br": 1390
      },
      {
        "zip": "46863",
        "rent2br": 1120,
        "rent3br": 1390
      },
      {
        "zip": "46869",
        "rent2br": 1120,
        "rent3br": 1390
      },
      {
        "zip": "46774",
        "rent2br": 1110,
        "rent3br": 1400
      },
      {
        "zip": "46777",
        "rent2br": 1070,
        "rent3br": 1300
      },
      {
        "zip": "46962",
        "rent2br": 1000,
        "rent3br": 1200
      },
      {
        "zip": "46773",
        "rent2br": 970,
        "rent3br": 1210
      },
      {
        "zip": "46809",
        "rent2br": 960,
        "rent3br": 1190
      }
    ]
  },
  "jackson": {
    "areaName": "Jackson, MS metro area",
    "year": 2026,
    "zipCount": 69,
    "rows": [
      {
        "zip": "39110",
        "rent2br": 1930,
        "rent3br": 2310
      },
      {
        "zip": "39043",
        "rent2br": 1450,
        "rent3br": 1740
      },
      {
        "zip": "39058",
        "rent2br": 1400,
        "rent3br": 1680
      },
      {
        "zip": "39154",
        "rent2br": 1330,
        "rent3br": 1590
      },
      {
        "zip": "39207",
        "rent2br": 1250,
        "rent3br": 1500
      },
      {
        "zip": "39283",
        "rent2br": 1250,
        "rent3br": 1500
      },
      {
        "zip": "39170",
        "rent2br": 1160,
        "rent3br": 1390
      },
      {
        "zip": "39046",
        "rent2br": 1080,
        "rent3br": 1290
      },
      {
        "zip": "39066",
        "rent2br": 1030,
        "rent3br": 1230
      },
      {
        "zip": "39051",
        "rent2br": 950,
        "rent3br": 1150
      },
      {
        "zip": "39078",
        "rent2br": 860,
        "rent3br": 1050
      },
      {
        "zip": "39654",
        "rent2br": 840,
        "rent3br": 1070
      }
    ]
  },
  "augusta": {
    "areaName": "Augusta-Richmond County, GA-SC metro area",
    "year": 2026,
    "zipCount": 64,
    "rows": [
      {
        "zip": "30809",
        "rent2br": 1890,
        "rent3br": 2440
      },
      {
        "zip": "30815",
        "rent2br": 1370,
        "rent3br": 1770
      },
      {
        "zip": "30912",
        "rent2br": 1270,
        "rent3br": 1640
      },
      {
        "zip": "29828",
        "rent2br": 1240,
        "rent3br": 1600
      },
      {
        "zip": "29822",
        "rent2br": 1200,
        "rent3br": 1550
      },
      {
        "zip": "29816",
        "rent2br": 1140,
        "rent3br": 1460
      },
      {
        "zip": "29164",
        "rent2br": 1080,
        "rent3br": 1390
      },
      {
        "zip": "29129",
        "rent2br": 1020,
        "rent3br": 1300
      },
      {
        "zip": "29842",
        "rent2br": 1010,
        "rent3br": 1300
      },
      {
        "zip": "30828",
        "rent2br": 980,
        "rent3br": 1290
      },
      {
        "zip": "29853",
        "rent2br": 970,
        "rent3br": 1190
      },
      {
        "zip": "30816",
        "rent2br": 970,
        "rent3br": 1250
      }
    ]
  },
  "fargo": {
    "areaName": "Fargo, ND-MN metro area",
    "year": 2026,
    "zipCount": 55,
    "rows": [
      {
        "zip": "56519",
        "rent2br": 1460,
        "rent3br": 1820
      },
      {
        "zip": "58078",
        "rent2br": 1240,
        "rent3br": 1720
      },
      {
        "zip": "58052",
        "rent2br": 1180,
        "rent3br": 1640
      },
      {
        "zip": "56529",
        "rent2br": 1150,
        "rent3br": 1600
      },
      {
        "zip": "58005",
        "rent2br": 1100,
        "rent3br": 1530
      },
      {
        "zip": "58106",
        "rent2br": 1100,
        "rent3br": 1530
      },
      {
        "zip": "58047",
        "rent2br": 1050,
        "rent3br": 1460
      },
      {
        "zip": "58068",
        "rent2br": 1020,
        "rent3br": 1370
      },
      {
        "zip": "56549",
        "rent2br": 980,
        "rent3br": 1360
      },
      {
        "zip": "56554",
        "rent2br": 970,
        "rent3br": 1270
      },
      {
        "zip": "58027",
        "rent2br": 970,
        "rent3br": 1270
      },
      {
        "zip": "58071",
        "rent2br": 970,
        "rent3br": 1350
      }
    ]
  },
  "wilmington": {
    "areaName": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD metro area",
    "year": 2026,
    "zipCount": 473,
    "rows": [
      {
        "zip": "08019",
        "rent2br": 2720,
        "rent3br": 3260
      },
      {
        "zip": "19355",
        "rent2br": 2450,
        "rent3br": 2940
      },
      {
        "zip": "19732",
        "rent2br": 2190,
        "rent3br": 2630
      },
      {
        "zip": "19040",
        "rent2br": 2080,
        "rent3br": 2490
      },
      {
        "zip": "19403",
        "rent2br": 2000,
        "rent3br": 2400
      },
      {
        "zip": "18955",
        "rent2br": 1910,
        "rent3br": 2290
      },
      {
        "zip": "19009",
        "rent2br": 1820,
        "rent3br": 2180
      },
      {
        "zip": "19899",
        "rent2br": 1780,
        "rent3br": 2130
      },
      {
        "zip": "19730",
        "rent2br": 1680,
        "rent3br": 2010
      },
      {
        "zip": "19464",
        "rent2br": 1610,
        "rent3br": 1930
      },
      {
        "zip": "19076",
        "rent2br": 1510,
        "rent3br": 1810
      },
      {
        "zip": "17536",
        "rent2br": 1130,
        "rent3br": 1470
      }
    ]
  },
  "harrisburg": {
    "areaName": "Harrisburg-Carlisle, PA metro area",
    "year": 2026,
    "zipCount": 82,
    "rows": [
      {
        "zip": "17050",
        "rent2br": 1880,
        "rent3br": 2420
      },
      {
        "zip": "17111",
        "rent2br": 1650,
        "rent3br": 2120
      },
      {
        "zip": "17027",
        "rent2br": 1520,
        "rent3br": 1980
      },
      {
        "zip": "17121",
        "rent2br": 1500,
        "rent3br": 1930
      },
      {
        "zip": "17129",
        "rent2br": 1500,
        "rent3br": 1930
      },
      {
        "zip": "17006",
        "rent2br": 1390,
        "rent3br": 1790
      },
      {
        "zip": "17048",
        "rent2br": 1300,
        "rent3br": 1670
      },
      {
        "zip": "17053",
        "rent2br": 1230,
        "rent3br": 1580
      },
      {
        "zip": "17098",
        "rent2br": 1140,
        "rent3br": 1470
      },
      {
        "zip": "17978",
        "rent2br": 1080,
        "rent3br": 1390
      },
      {
        "zip": "17030",
        "rent2br": 1040,
        "rent3br": 1340
      },
      {
        "zip": "17938",
        "rent2br": 1040,
        "rent3br": 1340
      }
    ]
  },
  "hartford": {
    "areaName": "Hartford-West Hartford-East Hartford, CT metro area",
    "year": 2026,
    "zipCount": 137,
    "rows": [
      {
        "zip": "06269",
        "rent2br": 2800,
        "rent3br": 3360
      },
      {
        "zip": "06117",
        "rent2br": 2360,
        "rent3br": 2830
      },
      {
        "zip": "06095",
        "rent2br": 2180,
        "rent3br": 2610
      },
      {
        "zip": "06066",
        "rent2br": 1960,
        "rent3br": 2350
      },
      {
        "zip": "06456",
        "rent2br": 1920,
        "rent3br": 2300
      },
      {
        "zip": "06412",
        "rent2br": 1870,
        "rent3br": 2240
      },
      {
        "zip": "06126",
        "rent2br": 1860,
        "rent3br": 2230
      },
      {
        "zip": "06144",
        "rent2br": 1860,
        "rent3br": 2230
      },
      {
        "zip": "06199",
        "rent2br": 1860,
        "rent3br": 2230
      },
      {
        "zip": "06231",
        "rent2br": 1770,
        "rent3br": 2120
      },
      {
        "zip": "06108",
        "rent2br": 1650,
        "rent3br": 1980
      },
      {
        "zip": "06237",
        "rent2br": 1300,
        "rent3br": 1560
      }
    ]
  },
  "stockton": {
    "areaName": "Stockton-Lodi, CA metro area",
    "year": 2026,
    "zipCount": 47,
    "rows": [
      {
        "zip": "94505",
        "rent2br": 3660,
        "rent3br": 4680
      },
      {
        "zip": "95230",
        "rent2br": 2430,
        "rent3br": 3380
      },
      {
        "zip": "95376",
        "rent2br": 2100,
        "rent3br": 2920
      },
      {
        "zip": "95231",
        "rent2br": 1930,
        "rent3br": 2680
      },
      {
        "zip": "95367",
        "rent2br": 1820,
        "rent3br": 2530
      },
      {
        "zip": "95208",
        "rent2br": 1740,
        "rent3br": 2420
      },
      {
        "zip": "95267",
        "rent2br": 1740,
        "rent3br": 2420
      },
      {
        "zip": "95690",
        "rent2br": 1720,
        "rent3br": 2290
      },
      {
        "zip": "95210",
        "rent2br": 1550,
        "rent3br": 2160
      },
      {
        "zip": "95258",
        "rent2br": 1530,
        "rent3br": 2130
      },
      {
        "zip": "95215",
        "rent2br": 1380,
        "rent3br": 1920
      },
      {
        "zip": "95686",
        "rent2br": 1310,
        "rent3br": 1840
      }
    ]
  },
  "mobile": {
    "areaName": "Mobile, AL metro area",
    "year": 2026,
    "zipCount": 50,
    "rows": [
      {
        "zip": "36528",
        "rent2br": 1480,
        "rent3br": 1930
      },
      {
        "zip": "36608",
        "rent2br": 1240,
        "rent3br": 1620
      },
      {
        "zip": "36575",
        "rent2br": 1150,
        "rent3br": 1500
      },
      {
        "zip": "36523",
        "rent2br": 1120,
        "rent3br": 1460
      },
      {
        "zip": "36590",
        "rent2br": 1080,
        "rent3br": 1410
      },
      {
        "zip": "36633",
        "rent2br": 1080,
        "rent3br": 1410
      },
      {
        "zip": "36685",
        "rent2br": 1080,
        "rent3br": 1410
      },
      {
        "zip": "36611",
        "rent2br": 1040,
        "rent3br": 1360
      },
      {
        "zip": "36560",
        "rent2br": 1000,
        "rent3br": 1310
      },
      {
        "zip": "36513",
        "rent2br": 960,
        "rent3br": 1260
      },
      {
        "zip": "36522",
        "rent2br": 900,
        "rent3br": 1180
      },
      {
        "zip": "36612",
        "rent2br": 900,
        "rent3br": 1180
      }
    ]
  },
  "beaumont": {
    "areaName": "Beaumont-Port Arthur, TX metro area",
    "year": 2026,
    "zipCount": 43,
    "rows": [
      {
        "zip": "77713",
        "rent2br": 1410,
        "rent3br": 1850
      },
      {
        "zip": "77707",
        "rent2br": 1230,
        "rent3br": 1610
      },
      {
        "zip": "77706",
        "rent2br": 1200,
        "rent3br": 1570
      },
      {
        "zip": "77651",
        "rent2br": 1150,
        "rent3br": 1510
      },
      {
        "zip": "77704",
        "rent2br": 1120,
        "rent3br": 1470
      },
      {
        "zip": "77708",
        "rent2br": 1100,
        "rent3br": 1440
      },
      {
        "zip": "77632",
        "rent2br": 1090,
        "rent3br": 1440
      },
      {
        "zip": "77631",
        "rent2br": 1060,
        "rent3br": 1390
      },
      {
        "zip": "77664",
        "rent2br": 1050,
        "rent3br": 1320
      },
      {
        "zip": "77519",
        "rent2br": 1030,
        "rent3br": 1350
      },
      {
        "zip": "77656",
        "rent2br": 1010,
        "rent3br": 1320
      },
      {
        "zip": "77705",
        "rent2br": 970,
        "rent3br": 1280
      }
    ]
  },
  "denton": {
    "areaName": "Dallas, TX metro area",
    "year": 2026,
    "zipCount": 260,
    "rows": [
      {
        "zip": "75072",
        "rent2br": 2900,
        "rent3br": 3650
      },
      {
        "zip": "75002",
        "rent2br": 2490,
        "rent3br": 3140
      },
      {
        "zip": "76051",
        "rent2br": 2330,
        "rent3br": 3070
      },
      {
        "zip": "75214",
        "rent2br": 2170,
        "rent3br": 2730
      },
      {
        "zip": "76202",
        "rent2br": 2020,
        "rent3br": 2540
      },
      {
        "zip": "75230",
        "rent2br": 1850,
        "rent3br": 2330
      },
      {
        "zip": "75270",
        "rent2br": 1840,
        "rent3br": 2320
      },
      {
        "zip": "75135",
        "rent2br": 1830,
        "rent3br": 2300
      },
      {
        "zip": "75252",
        "rent2br": 1720,
        "rent3br": 2170
      },
      {
        "zip": "76623",
        "rent2br": 1550,
        "rent3br": 1950
      },
      {
        "zip": "75217",
        "rent2br": 1410,
        "rent3br": 1780
      },
      {
        "zip": "75156",
        "rent2br": 1030,
        "rent3br": 1300
      }
    ]
  },
  "mesa": {
    "areaName": "Phoenix-Mesa-Chandler, AZ metro area",
    "year": 2026,
    "zipCount": 225,
    "rows": [
      {
        "zip": "85045",
        "rent2br": 2760,
        "rent3br": 3680
      },
      {
        "zip": "85388",
        "rent2br": 2470,
        "rent3br": 3290
      },
      {
        "zip": "85140",
        "rent2br": 2250,
        "rent3br": 3000
      },
      {
        "zip": "85024",
        "rent2br": 2100,
        "rent3br": 2800
      },
      {
        "zip": "85018",
        "rent2br": 1930,
        "rent3br": 2570
      },
      {
        "zip": "85063",
        "rent2br": 1840,
        "rent3br": 2450
      },
      {
        "zip": "85244",
        "rent2br": 1840,
        "rent3br": 2450
      },
      {
        "zip": "85380",
        "rent2br": 1840,
        "rent3br": 2450
      },
      {
        "zip": "85029",
        "rent2br": 1710,
        "rent3br": 2280
      },
      {
        "zip": "85035",
        "rent2br": 1590,
        "rent3br": 2120
      },
      {
        "zip": "85128",
        "rent2br": 1530,
        "rent3br": 2070
      },
      {
        "zip": "85634",
        "rent2br": 1530,
        "rent3br": 2070
      }
    ]
  },
  "olathe": {
    "areaName": "Kansas City, MO-KS metro area",
    "year": 2026,
    "zipCount": 251,
    "rows": [
      {
        "zip": "64157",
        "rent2br": 2040,
        "rent3br": 2660
      },
      {
        "zip": "66211",
        "rent2br": 1670,
        "rent3br": 2180
      },
      {
        "zip": "64064",
        "rent2br": 1550,
        "rent3br": 2020
      },
      {
        "zip": "64018",
        "rent2br": 1460,
        "rent3br": 1900
      },
      {
        "zip": "64144",
        "rent2br": 1360,
        "rent3br": 1770
      },
      {
        "zip": "64057",
        "rent2br": 1300,
        "rent3br": 1690
      },
      {
        "zip": "66083",
        "rent2br": 1250,
        "rent3br": 1630
      },
      {
        "zip": "64117",
        "rent2br": 1180,
        "rent3br": 1540
      },
      {
        "zip": "64746",
        "rent2br": 1110,
        "rent3br": 1450
      },
      {
        "zip": "64017",
        "rent2br": 1030,
        "rent3br": 1350
      },
      {
        "zip": "64644",
        "rent2br": 1030,
        "rent3br": 1350
      },
      {
        "zip": "66767",
        "rent2br": 1030,
        "rent3br": 1350
      }
    ]
  },
  "montgomery": {
    "areaName": "Montgomery, AL metro area",
    "year": 2026,
    "zipCount": 66,
    "rows": [
      {
        "zip": "36113",
        "rent2br": 1520,
        "rent3br": 1950
      },
      {
        "zip": "36112",
        "rent2br": 1290,
        "rent3br": 1620
      },
      {
        "zip": "36025",
        "rent2br": 1080,
        "rent3br": 1390
      },
      {
        "zip": "36051",
        "rent2br": 1020,
        "rent3br": 1310
      },
      {
        "zip": "36121",
        "rent2br": 1010,
        "rent3br": 1300
      },
      {
        "zip": "36043",
        "rent2br": 1000,
        "rent3br": 1280
      },
      {
        "zip": "36036",
        "rent2br": 960,
        "rent3br": 1200
      },
      {
        "zip": "36105",
        "rent2br": 930,
        "rent3br": 1190
      },
      {
        "zip": "36029",
        "rent2br": 900,
        "rent3br": 1130
      },
      {
        "zip": "36069",
        "rent2br": 900,
        "rent3br": 1130
      },
      {
        "zip": "36701",
        "rent2br": 900,
        "rent3br": 1180
      },
      {
        "zip": "36785",
        "rent2br": 900,
        "rent3br": 1150
      }
    ]
  },
  "norfolk": {
    "areaName": "Virginia Beach-Norfolk-Newport News, VA-NC metro area",
    "year": 2026,
    "zipCount": 152,
    "rows": [
      {
        "zip": "23511",
        "rent2br": 2440,
        "rent3br": 3380
      },
      {
        "zip": "23433",
        "rent2br": 2090,
        "rent3br": 2900
      },
      {
        "zip": "23454",
        "rent2br": 1970,
        "rent3br": 2730
      },
      {
        "zip": "23328",
        "rent2br": 1840,
        "rent3br": 2550
      },
      {
        "zip": "23606",
        "rent2br": 1730,
        "rent3br": 2400
      },
      {
        "zip": "27958",
        "rent2br": 1650,
        "rent3br": 2300
      },
      {
        "zip": "27929",
        "rent2br": 1590,
        "rent3br": 2200
      },
      {
        "zip": "23609",
        "rent2br": 1550,
        "rent3br": 2150
      },
      {
        "zip": "27939",
        "rent2br": 1460,
        "rent3br": 2020
      },
      {
        "zip": "23068",
        "rent2br": 1410,
        "rent3br": 1960
      },
      {
        "zip": "23183",
        "rent2br": 1400,
        "rent3br": 1940
      },
      {
        "zip": "23851",
        "rent2br": 1100,
        "rent3br": 1440
      }
    ]
  },
  "virginia-beach": {
    "areaName": "Virginia Beach-Norfolk-Newport News, VA-NC metro area",
    "year": 2026,
    "zipCount": 152,
    "rows": [
      {
        "zip": "23511",
        "rent2br": 2440,
        "rent3br": 3380
      },
      {
        "zip": "23433",
        "rent2br": 2090,
        "rent3br": 2900
      },
      {
        "zip": "23454",
        "rent2br": 1970,
        "rent3br": 2730
      },
      {
        "zip": "23328",
        "rent2br": 1840,
        "rent3br": 2550
      },
      {
        "zip": "23606",
        "rent2br": 1730,
        "rent3br": 2400
      },
      {
        "zip": "27958",
        "rent2br": 1650,
        "rent3br": 2300
      },
      {
        "zip": "27929",
        "rent2br": 1590,
        "rent3br": 2200
      },
      {
        "zip": "23609",
        "rent2br": 1550,
        "rent3br": 2150
      },
      {
        "zip": "27939",
        "rent2br": 1460,
        "rent3br": 2020
      },
      {
        "zip": "23068",
        "rent2br": 1410,
        "rent3br": 1960
      },
      {
        "zip": "23183",
        "rent2br": 1400,
        "rent3br": 1940
      },
      {
        "zip": "23851",
        "rent2br": 1100,
        "rent3br": 1440
      }
    ]
  },
  "charleston": {
    "areaName": "Charleston-North Charleston, SC metro area",
    "year": 2026,
    "zipCount": 62,
    "rows": [
      {
        "zip": "29451",
        "rent2br": 2680,
        "rent3br": 3330
      },
      {
        "zip": "29424",
        "rent2br": 2270,
        "rent3br": 2830
      },
      {
        "zip": "29412",
        "rent2br": 2130,
        "rent3br": 2650
      },
      {
        "zip": "29402",
        "rent2br": 1820,
        "rent3br": 2260
      },
      {
        "zip": "29419",
        "rent2br": 1820,
        "rent3br": 2260
      },
      {
        "zip": "29450",
        "rent2br": 1810,
        "rent3br": 2250
      },
      {
        "zip": "29485",
        "rent2br": 1760,
        "rent3br": 2190
      },
      {
        "zip": "29405",
        "rent2br": 1540,
        "rent3br": 1920
      },
      {
        "zip": "29434",
        "rent2br": 1410,
        "rent3br": 1760
      },
      {
        "zip": "29059",
        "rent2br": 1300,
        "rent3br": 1620
      },
      {
        "zip": "29449",
        "rent2br": 1300,
        "rent3br": 1620
      },
      {
        "zip": "29481",
        "rent2br": 1300,
        "rent3br": 1620
      }
    ]
  },
  "sarasota": {
    "areaName": "North Port-Bradenton-Sarasota, FL metro area",
    "year": 2026,
    "zipCount": 63,
    "rows": [
      {
        "zip": "34228",
        "rent2br": 2940,
        "rent3br": 3810
      },
      {
        "zip": "34219",
        "rent2br": 2410,
        "rent3br": 3120
      },
      {
        "zip": "34236",
        "rent2br": 2340,
        "rent3br": 3030
      },
      {
        "zip": "34251",
        "rent2br": 2200,
        "rent3br": 2870
      },
      {
        "zip": "34209",
        "rent2br": 2100,
        "rent3br": 2720
      },
      {
        "zip": "34249",
        "rent2br": 2050,
        "rent3br": 2660
      },
      {
        "zip": "34290",
        "rent2br": 2050,
        "rent3br": 2660
      },
      {
        "zip": "34204",
        "rent2br": 1850,
        "rent3br": 2400
      },
      {
        "zip": "34270",
        "rent2br": 1850,
        "rent3br": 2400
      },
      {
        "zip": "34208",
        "rent2br": 1750,
        "rent3br": 2270
      },
      {
        "zip": "34207",
        "rent2br": 1670,
        "rent3br": 2160
      },
      {
        "zip": "34224",
        "rent2br": 1370,
        "rent3br": 1900
      }
    ]
  },
  "pueblo": {
    "areaName": "Pueblo, CO metro area",
    "year": 2026,
    "zipCount": 17,
    "rows": [
      {
        "zip": "80817",
        "rent2br": 1940,
        "rent3br": 2700
      },
      {
        "zip": "81008",
        "rent2br": 1650,
        "rent3br": 2100
      },
      {
        "zip": "81007",
        "rent2br": 1560,
        "rent3br": 1990
      },
      {
        "zip": "81019",
        "rent2br": 1440,
        "rent3br": 1830
      },
      {
        "zip": "81062",
        "rent2br": 1290,
        "rent3br": 1550
      },
      {
        "zip": "81002",
        "rent2br": 1270,
        "rent3br": 1620
      },
      {
        "zip": "81004",
        "rent2br": 1230,
        "rent3br": 1570
      },
      {
        "zip": "81001",
        "rent2br": 1220,
        "rent3br": 1550
      },
      {
        "zip": "81023",
        "rent2br": 1180,
        "rent3br": 1490
      },
      {
        "zip": "81253",
        "rent2br": 1170,
        "rent3br": 1480
      },
      {
        "zip": "81069",
        "rent2br": 1070,
        "rent3br": 1350
      },
      {
        "zip": "81039",
        "rent2br": 980,
        "rent3br": 1300
      }
    ]
  },
  "paterson": {
    "areaName": "Bergen-Passaic, NJ metro area",
    "year": 2026,
    "zipCount": 114,
    "rows": [
      {
        "zip": "07020",
        "rent2br": 3490,
        "rent3br": 4260
      },
      {
        "zip": "07620",
        "rent2br": 3280,
        "rent3br": 4000
      },
      {
        "zip": "07458",
        "rent2br": 3000,
        "rent3br": 3670
      },
      {
        "zip": "07630",
        "rent2br": 2770,
        "rent3br": 3380
      },
      {
        "zip": "07014",
        "rent2br": 2620,
        "rent3br": 3200
      },
      {
        "zip": "07403",
        "rent2br": 2480,
        "rent3br": 3020
      },
      {
        "zip": "07073",
        "rent2br": 2410,
        "rent3br": 2940
      },
      {
        "zip": "07436",
        "rent2br": 2340,
        "rent3br": 2850
      },
      {
        "zip": "07011",
        "rent2br": 2250,
        "rent3br": 2740
      },
      {
        "zip": "07026",
        "rent2br": 2130,
        "rent3br": 2600
      },
      {
        "zip": "07480",
        "rent2br": 2020,
        "rent3br": 2460
      },
      {
        "zip": "07074",
        "rent2br": 1490,
        "rent3br": 1820
      }
    ]
  }
};
