/**
 * TrueCap Investor Index aggregation contract v1.
 *
 * This module is intentionally pure and storage-agnostic. It accepts only
 * records that an upstream, server-only provider has already deemed eligible
 * for aggregate use, and returns a deliberately narrow public-release shape.
 * Exact timestamps, addresses, coordinates, record IDs, and contributor IDs
 * are never copied into the result.
 *
 * Privacy is enforced in layers:
 * - explicit aggregate eligibility (default-deny upstream contract),
 * - calendar-quarter and national/state/CBSA-only buckets,
 * - a minimum observation AND distinct-contributor threshold,
 * - a per-contributor contribution cap,
 * - banded (not exact) sample sizes,
 * - per-metric suppression when coverage or definition versions are unsafe.
 */

export const INVESTOR_INDEX_CONTRACT_VERSION = "1.0" as const;

export const INVESTOR_INDEX_PRIVACY_POLICY = Object.freeze({
  version: "1.0",
  minimumObservations: 25,
  minimumDistinctContributors: 10,
  maximumObservationsPerContributorPerCohort: 5,
  timeGranularity: "calendar-quarter",
  geographyGranularity: ["national", "state", "metro"] as const,
  volumePrecision: "banded",
});

export type InvestorIndexGeography =
  | { level: "national"; countryCode: "US" }
  | { level: "state"; countryCode: "US"; regionCode: string }
  | { level: "metro"; countryCode: "US"; marketCode: string };

export const INVESTOR_INDEX_LIMITING_ASSUMPTIONS = [
  "purchase-price",
  "rent",
  "interest-rate",
  "property-taxes",
  "insurance",
  "operating-expenses",
  "rehab-budget",
  "down-payment",
  "closing-costs",
  "other",
] as const;

export type InvestorIndexLimitingAssumption =
  (typeof INVESTOR_INDEX_LIMITING_ASSUMPTIONS)[number];

/**
 * Input to the pure aggregator. `privacyRecordKey` and
 * `privacyContributorKey` should be stable HMACs generated by a server-only
 * provider, not raw database IDs. They are used only for deduplication and
 * contribution limiting and are never returned.
 */
export type InvestorIndexObservation = {
  privacyRecordKey: string;
  privacyContributorKey: string;
  aggregateEligibility: "approved" | "not-approved";
  analyzedAt: string | Date;
  geography: InvestorIndexGeography;
  metrics: {
    /** Canonical underwriting method used for the three return metrics. */
    underwritingMethodVersion?: string | null;
    standardScreen?: "pass" | "fail" | null;
    /** Frozen definition of the standard screen (for example DSCR-v1). */
    standardScreenDefinitionVersion?: string | null;
    capRatePct?: number | null;
    cashOnCashReturnPct?: number | null;
    monthlyCashFlow?: number | null;
    askingPrice?: number | null;
    maxOffer?: number | null;
    /** Frozen target set / solver definition used to calculate Max Offer. */
    maxOfferDefinitionVersion?: string | null;
    limitingAssumption?: InvestorIndexLimitingAssumption | null;
    /** Frozen decision-threshold definition used to pick the limiter. */
    limitingAssumptionDefinitionVersion?: string | null;
    inputConfidence?: {
      score: number;
      methodVersion: string;
    } | null;
  };
};

export type InvestorIndexVolumeBand = {
  label: "25–49" | "50–99" | "100–249" | "250–499" | "500–999" | "1,000+";
  lowerBound: 25 | 50 | 100 | 250 | 500 | 1_000;
  upperBound: 49 | 99 | 249 | 499 | 999 | null;
};

export type InvestorIndexSuppressionReason =
  | "insufficient-data"
  | "mixed-definition-versions"
  | "no-comparable-prior-period";

export type InvestorIndexMetric<T> =
  | {
      status: "published";
      value: T;
      sampleSize: InvestorIndexVolumeBand;
      definitionVersion: string;
    }
  | {
      status: "suppressed";
      reason: InvestorIndexSuppressionReason;
    };

export type InvestorIndexCohort = {
  cohortKey: string;
  period: {
    granularity: "calendar-quarter";
    key: string;
    year: number;
    quarter: 1 | 2 | 3 | 4;
  };
  geography: InvestorIndexGeography;
  /** Banded by design; the public contract never exposes an exact row count. */
  analysisVolume: InvestorIndexVolumeBand;
  passRatePct: InvestorIndexMetric<number>;
  medianCapRatePct: InvestorIndexMetric<number>;
  medianCashOnCashReturnPct: InvestorIndexMetric<number>;
  medianMonthlyCashFlow: InvestorIndexMetric<number>;
  askingVsMaxOfferGap: InvestorIndexMetric<{
    medianGapDollars: number;
    medianGapPctOfAsking: number;
  }>;
  mostLimitingAssumption: InvestorIndexMetric<{
    assumption: InvestorIndexLimitingAssumption;
    sharePct: number;
  }>;
  /**
   * Published only when the current and prior quarter each have a sufficiently
   * large, contributor-diverse set of Input Confidence snapshots calculated
   * with the same method version.
   */
  inputConfidenceTrend: InvestorIndexMetric<{
    currentMedianScore: number;
    previousMedianScore: number;
    changePoints: number;
    direction: "up" | "flat" | "down";
    comparedWithPeriod: string;
  }>;
};

export type InvestorIndexRelease = {
  contractVersion: typeof INVESTOR_INDEX_CONTRACT_VERSION;
  privacyPolicy: typeof INVESTOR_INDEX_PRIVACY_POLICY;
  cohorts: InvestorIndexCohort[];
};

type Quarter = InvestorIndexCohort["period"];

type NormalizedMetrics = {
  underwritingMethodVersion: string | null;
  standardScreen: "pass" | "fail" | null;
  standardScreenDefinitionVersion: string | null;
  capRatePct: number | null;
  cashOnCashReturnPct: number | null;
  monthlyCashFlow: number | null;
  askingPrice: number | null;
  maxOffer: number | null;
  maxOfferDefinitionVersion: string | null;
  limitingAssumption: InvestorIndexLimitingAssumption | null;
  limitingAssumptionDefinitionVersion: string | null;
  inputConfidence: { score: number; methodVersion: string } | null;
};

type NormalizedObservation = {
  privacyRecordKey: string;
  privacyContributorKey: string;
  analyzedAtMs: number;
  geography: InvestorIndexGeography;
  geographyKey: string;
  period: Quarter;
  metrics: NormalizedMetrics;
  deterministicTieBreak: string;
};

type CohortWork = {
  geography: InvestorIndexGeography;
  geographyKey: string;
  period: Quarter;
  records: NormalizedObservation[];
};

const LIMITING_ASSUMPTION_SET = new Set<string>(INVESTOR_INDEX_LIMITING_ASSUMPTIONS);

function finiteInRange(value: unknown, minimum: number, maximum: number): number | null {
  if (typeof value !== "number" || !Number.isFinite(value)) return null;
  if (value < minimum || value > maximum) return null;
  return value;
}

function normalizedVersion(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  // Definition versions are identifiers, not user-authored labels.
  return /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/.test(trimmed) ? trimmed : null;
}

function normalizeGeography(value: unknown): {
  geography: InvestorIndexGeography;
  key: string;
} | null {
  if (!value || typeof value !== "object") return null;
  const raw = value as Record<string, unknown>;
  if (raw.countryCode !== "US") return null;

  if (raw.level === "national") {
    return { geography: { level: "national", countryCode: "US" }, key: "US" };
  }

  if (raw.level === "state" && typeof raw.regionCode === "string") {
    const regionCode = raw.regionCode.trim().toUpperCase();
    if (!/^[A-Z]{2}$/.test(regionCode)) return null;
    return {
      geography: { level: "state", countryCode: "US", regionCode },
      key: `US-STATE-${regionCode}`,
    };
  }

  if (raw.level === "metro" && typeof raw.marketCode === "string") {
    const marketCode = raw.marketCode.trim();
    // US Census Core Based Statistical Area code. Labels are intentionally
    // resolved outside the aggregate rather than accepting arbitrary text.
    if (!/^\d{5}$/.test(marketCode)) return null;
    return {
      geography: { level: "metro", countryCode: "US", marketCode },
      key: `US-CBSA-${marketCode}`,
    };
  }

  return null;
}

export function toInvestorIndexQuarter(value: string | Date): Quarter | null {
  const date = value instanceof Date ? new Date(value.getTime()) : new Date(value);
  const timestamp = date.getTime();
  if (!Number.isFinite(timestamp)) return null;
  const year = date.getUTCFullYear();
  // Keep malformed/far-future provider data out of published aggregates.
  if (year < 2000 || year > 2100) return null;
  const quarter = (Math.floor(date.getUTCMonth() / 3) + 1) as 1 | 2 | 3 | 4;
  return {
    granularity: "calendar-quarter",
    key: `${year}-Q${quarter}`,
    year,
    quarter,
  };
}

function normalizeMetrics(value: InvestorIndexObservation["metrics"]): NormalizedMetrics {
  const limitingAssumption =
    typeof value.limitingAssumption === "string" &&
    LIMITING_ASSUMPTION_SET.has(value.limitingAssumption)
      ? (value.limitingAssumption as InvestorIndexLimitingAssumption)
      : null;
  const inputScore = finiteInRange(value.inputConfidence?.score, 0, 100);
  const inputMethodVersion = normalizedVersion(value.inputConfidence?.methodVersion);

  return {
    underwritingMethodVersion: normalizedVersion(value.underwritingMethodVersion),
    standardScreen:
      value.standardScreen === "pass" || value.standardScreen === "fail"
        ? value.standardScreen
        : null,
    standardScreenDefinitionVersion: normalizedVersion(
      value.standardScreenDefinitionVersion
    ),
    // Broad guards reject corrupt/overflow values without pretending that
    // normal weak or exceptional deals cannot exist.
    capRatePct: finiteInRange(value.capRatePct, -100, 100),
    cashOnCashReturnPct: finiteInRange(value.cashOnCashReturnPct, -1_000, 1_000),
    monthlyCashFlow: finiteInRange(value.monthlyCashFlow, -10_000_000, 10_000_000),
    askingPrice: finiteInRange(value.askingPrice, 1, 1_000_000_000),
    maxOffer: finiteInRange(value.maxOffer, 0, 1_000_000_000),
    maxOfferDefinitionVersion: normalizedVersion(value.maxOfferDefinitionVersion),
    limitingAssumption,
    limitingAssumptionDefinitionVersion: normalizedVersion(
      value.limitingAssumptionDefinitionVersion
    ),
    inputConfidence:
      inputScore !== null && inputMethodVersion
        ? { score: inputScore, methodVersion: inputMethodVersion }
        : null,
  };
}

function normalizeObservation(value: InvestorIndexObservation): NormalizedObservation | null {
  if (value.aggregateEligibility !== "approved") return null;
  if (typeof value.privacyRecordKey !== "string" || !value.privacyRecordKey.trim()) return null;
  if (
    typeof value.privacyContributorKey !== "string" ||
    !value.privacyContributorKey.trim()
  ) {
    return null;
  }
  const period = toInvestorIndexQuarter(value.analyzedAt);
  const analyzedAt = value.analyzedAt instanceof Date ? value.analyzedAt : new Date(value.analyzedAt);
  const analyzedAtMs = analyzedAt.getTime();
  const geography = normalizeGeography(value.geography);
  if (!period || !Number.isFinite(analyzedAtMs) || !geography) return null;

  const metrics = normalizeMetrics(value.metrics ?? {});
  return {
    privacyRecordKey: value.privacyRecordKey.trim(),
    privacyContributorKey: value.privacyContributorKey.trim(),
    analyzedAtMs,
    geography: geography.geography,
    geographyKey: geography.key,
    period,
    metrics,
    deterministicTieBreak: JSON.stringify(metrics),
  };
}

function compareNormalized(a: NormalizedObservation, b: NormalizedObservation): number {
  return (
    a.analyzedAtMs - b.analyzedAtMs ||
    a.privacyRecordKey.localeCompare(b.privacyRecordKey) ||
    a.privacyContributorKey.localeCompare(b.privacyContributorKey) ||
    a.geographyKey.localeCompare(b.geographyKey) ||
    a.deterministicTieBreak.localeCompare(b.deterministicTieBreak)
  );
}

function bandVolume(count: number): InvestorIndexVolumeBand {
  if (count >= 1_000) return { label: "1,000+", lowerBound: 1_000, upperBound: null };
  if (count >= 500) return { label: "500–999", lowerBound: 500, upperBound: 999 };
  if (count >= 250) return { label: "250–499", lowerBound: 250, upperBound: 499 };
  if (count >= 100) return { label: "100–249", lowerBound: 100, upperBound: 249 };
  if (count >= 50) return { label: "50–99", lowerBound: 50, upperBound: 99 };
  return { label: "25–49", lowerBound: 25, upperBound: 49 };
}

function hasSafeCoverage(records: readonly NormalizedObservation[]): boolean {
  if (records.length < INVESTOR_INDEX_PRIVACY_POLICY.minimumObservations) return false;
  return (
    new Set(records.map((record) => record.privacyContributorKey)).size >=
    INVESTOR_INDEX_PRIVACY_POLICY.minimumDistinctContributors
  );
}

function suppressed(
  reason: InvestorIndexSuppressionReason
): InvestorIndexMetric<never> {
  return { status: "suppressed", reason };
}

function roundTo(value: number, increment: number): number {
  const rounded = Math.round(value / increment) * increment;
  // Avoid serializing -0, which is needlessly surprising in editorial data.
  return Object.is(rounded, -0) ? 0 : rounded;
}

function median(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);
  if (sorted.length % 2 === 1) return sorted[middle];
  return (sorted[middle - 1] + sorted[middle]) / 2;
}

function metricSubset<T>(
  records: readonly NormalizedObservation[],
  select: (record: NormalizedObservation) => { value: T; definitionVersion: string } | null
): {
  rows: { record: NormalizedObservation; value: T; definitionVersion: string }[];
  definitionVersion: string | null;
  unsafeMixedVersions: boolean;
} {
  const rows = records.flatMap((record) => {
    const selected = select(record);
    return selected ? [{ record, ...selected }] : [];
  });
  const versions = new Set(rows.map((row) => row.definitionVersion));
  return {
    rows,
    definitionVersion: versions.size === 1 ? rows[0]?.definitionVersion ?? null : null,
    unsafeMixedVersions: versions.size > 1,
  };
}

function publishNumberMetric(
  records: readonly NormalizedObservation[],
  select: (record: NormalizedObservation) => { value: number; definitionVersion: string } | null,
  aggregate: (values: readonly number[]) => number
): InvestorIndexMetric<number> {
  const subset = metricSubset(records, select);
  if (!hasSafeCoverage(subset.rows.map((row) => row.record))) {
    return suppressed("insufficient-data");
  }
  if (subset.unsafeMixedVersions || !subset.definitionVersion) {
    return suppressed("mixed-definition-versions");
  }
  return {
    status: "published",
    value: aggregate(subset.rows.map((row) => row.value)),
    sampleSize: bandVolume(subset.rows.length),
    definitionVersion: subset.definitionVersion,
  };
}

function buildPassRate(records: readonly NormalizedObservation[]): InvestorIndexMetric<number> {
  return publishNumberMetric(
    records,
    (record) => {
      const outcome = record.metrics.standardScreen;
      const version = record.metrics.standardScreenDefinitionVersion;
      return outcome && version
        ? { value: outcome === "pass" ? 1 : 0, definitionVersion: version }
        : null;
    },
    (values) => roundTo((values.reduce((sum, value) => sum + value, 0) / values.length) * 100, 5)
  );
}

function buildMedianMetric(
  records: readonly NormalizedObservation[],
  selectValue: (metrics: NormalizedMetrics) => number | null,
  roundingIncrement: number
): InvestorIndexMetric<number> {
  return publishNumberMetric(
    records,
    (record) => {
      const value = selectValue(record.metrics);
      const version = record.metrics.underwritingMethodVersion;
      return value !== null && version ? { value, definitionVersion: version } : null;
    },
    (values) => roundTo(median(values), roundingIncrement)
  );
}

function buildGap(
  records: readonly NormalizedObservation[]
): InvestorIndexCohort["askingVsMaxOfferGap"] {
  const subset = metricSubset(records, (record) => {
    const { askingPrice, maxOffer, underwritingMethodVersion, maxOfferDefinitionVersion } =
      record.metrics;
    if (
      askingPrice === null ||
      maxOffer === null ||
      !underwritingMethodVersion ||
      !maxOfferDefinitionVersion
    ) {
      return null;
    }
    return {
      value: {
        dollars: askingPrice - maxOffer,
        pct: ((askingPrice - maxOffer) / askingPrice) * 100,
      },
      definitionVersion: `${underwritingMethodVersion}:${maxOfferDefinitionVersion}`,
    };
  });
  if (!hasSafeCoverage(subset.rows.map((row) => row.record))) {
    return suppressed("insufficient-data");
  }
  if (subset.unsafeMixedVersions || !subset.definitionVersion) {
    return suppressed("mixed-definition-versions");
  }
  return {
    status: "published",
    value: {
      medianGapDollars: roundTo(
        median(subset.rows.map((row) => row.value.dollars)),
        1_000
      ),
      medianGapPctOfAsking: roundTo(
        median(subset.rows.map((row) => row.value.pct)),
        0.5
      ),
    },
    sampleSize: bandVolume(subset.rows.length),
    definitionVersion: subset.definitionVersion,
  };
}

function buildMostLimitingAssumption(
  records: readonly NormalizedObservation[]
): InvestorIndexCohort["mostLimitingAssumption"] {
  const subset = metricSubset(records, (record) => {
    const value = record.metrics.limitingAssumption;
    const version = record.metrics.limitingAssumptionDefinitionVersion;
    return value && version ? { value, definitionVersion: version } : null;
  });
  if (!hasSafeCoverage(subset.rows.map((row) => row.record))) {
    return suppressed("insufficient-data");
  }
  if (subset.unsafeMixedVersions || !subset.definitionVersion) {
    return suppressed("mixed-definition-versions");
  }

  const counts = new Map<InvestorIndexLimitingAssumption, number>();
  for (const row of subset.rows) counts.set(row.value, (counts.get(row.value) ?? 0) + 1);
  const winner = INVESTOR_INDEX_LIMITING_ASSUMPTIONS.reduce((best, candidate) => {
    const candidateCount = counts.get(candidate) ?? 0;
    const bestCount = counts.get(best) ?? 0;
    return candidateCount > bestCount ? candidate : best;
  });

  return {
    status: "published",
    value: {
      assumption: winner,
      sharePct: roundTo(((counts.get(winner) ?? 0) / subset.rows.length) * 100, 5),
    },
    sampleSize: bandVolume(subset.rows.length),
    definitionVersion: subset.definitionVersion,
  };
}

function previousQuarter(period: Quarter): Quarter {
  if (period.quarter === 1) {
    return {
      granularity: "calendar-quarter",
      key: `${period.year - 1}-Q4`,
      year: period.year - 1,
      quarter: 4,
    };
  }
  const quarter = (period.quarter - 1) as 1 | 2 | 3;
  return {
    granularity: "calendar-quarter",
    key: `${period.year}-Q${quarter}`,
    year: period.year,
    quarter,
  };
}

function inputConfidenceSubset(records: readonly NormalizedObservation[]) {
  return metricSubset(records, (record) => {
    const value = record.metrics.inputConfidence;
    return value
      ? { value: value.score, definitionVersion: value.methodVersion }
      : null;
  });
}

function buildInputConfidenceTrend(
  cohort: CohortWork,
  cohortMap: ReadonlyMap<string, CohortWork>
): InvestorIndexCohort["inputConfidenceTrend"] {
  const priorPeriod = previousQuarter(cohort.period);
  const prior = cohortMap.get(`${cohort.geographyKey}|${priorPeriod.key}`);
  if (!prior) return suppressed("no-comparable-prior-period");

  const currentSubset = inputConfidenceSubset(cohort.records);
  const priorSubset = inputConfidenceSubset(prior.records);
  if (
    !hasSafeCoverage(currentSubset.rows.map((row) => row.record)) ||
    !hasSafeCoverage(priorSubset.rows.map((row) => row.record))
  ) {
    return suppressed("insufficient-data");
  }
  if (
    currentSubset.unsafeMixedVersions ||
    priorSubset.unsafeMixedVersions ||
    !currentSubset.definitionVersion ||
    currentSubset.definitionVersion !== priorSubset.definitionVersion
  ) {
    return suppressed("mixed-definition-versions");
  }

  const currentMedianScore = roundTo(
    median(currentSubset.rows.map((row) => row.value)),
    1
  );
  const previousMedianScore = roundTo(
    median(priorSubset.rows.map((row) => row.value)),
    1
  );
  const changePoints = roundTo(currentMedianScore - previousMedianScore, 1);
  return {
    status: "published",
    value: {
      currentMedianScore,
      previousMedianScore,
      changePoints,
      direction: changePoints > 0 ? "up" : changePoints < 0 ? "down" : "flat",
      comparedWithPeriod: priorPeriod.key,
    },
    // The trend is only as strong as its smaller side. Returning a band for
    // that minimum avoids exposing either exact quarter count.
    sampleSize: bandVolume(Math.min(currentSubset.rows.length, priorSubset.rows.length)),
    definitionVersion: currentSubset.definitionVersion,
  };
}

function buildCohortMap(records: readonly NormalizedObservation[]): Map<string, CohortWork> {
  const map = new Map<string, CohortWork>();
  for (const record of records) {
    const key = `${record.geographyKey}|${record.period.key}`;
    const existing = map.get(key);
    if (existing) {
      existing.records.push(record);
    } else {
      map.set(key, {
        geography: record.geography,
        geographyKey: record.geographyKey,
        period: record.period,
        records: [record],
      });
    }
  }

  // A single actor cannot create a publishable cohort or dominate its metrics.
  for (const cohort of map.values()) {
    cohort.records.sort(compareNormalized);
    const contributorCounts = new Map<string, number>();
    cohort.records = cohort.records.filter((record) => {
      const count = contributorCounts.get(record.privacyContributorKey) ?? 0;
      if (count >= INVESTOR_INDEX_PRIVACY_POLICY.maximumObservationsPerContributorPerCohort) {
        return false;
      }
      contributorCounts.set(record.privacyContributorKey, count + 1);
      return true;
    });
  }
  return map;
}

/**
 * Build a privacy-safe, editorially consumable release. Cohorts that do not
 * satisfy both privacy thresholds are omitted entirely. Individual metrics
 * remain present but suppressed when their own eligible subset is too small or
 * mixes incompatible method/definition versions.
 */
export function aggregateInvestorIndex(
  observations: readonly InvestorIndexObservation[]
): InvestorIndexRelease {
  const normalized = observations
    .map(normalizeObservation)
    .filter((record): record is NormalizedObservation => record !== null)
    .sort(compareNormalized);

  // Dedupe globally before cohorting. A provider retry must not increase a
  // quarter's volume, and a duplicated key cannot count in two quarters.
  const seenRecordKeys = new Set<string>();
  const deduplicated = normalized.filter((record) => {
    if (seenRecordKeys.has(record.privacyRecordKey)) return false;
    seenRecordKeys.add(record.privacyRecordKey);
    return true;
  });

  const cohortMap = buildCohortMap(deduplicated);
  const publishable = [...cohortMap.values()]
    .filter((cohort) => hasSafeCoverage(cohort.records))
    .sort(
      (a, b) =>
        a.geographyKey.localeCompare(b.geographyKey) ||
        a.period.key.localeCompare(b.period.key)
    );

  const cohorts = publishable.map<InvestorIndexCohort>((cohort) => ({
    cohortKey: `${cohort.geographyKey}:${cohort.period.key}`,
    period: cohort.period,
    geography: cohort.geography,
    analysisVolume: bandVolume(cohort.records.length),
    passRatePct: buildPassRate(cohort.records),
    medianCapRatePct: buildMedianMetric(cohort.records, (metrics) => metrics.capRatePct, 0.1),
    medianCashOnCashReturnPct: buildMedianMetric(
      cohort.records,
      (metrics) => metrics.cashOnCashReturnPct,
      0.1
    ),
    medianMonthlyCashFlow: buildMedianMetric(
      cohort.records,
      (metrics) => metrics.monthlyCashFlow,
      25
    ),
    askingVsMaxOfferGap: buildGap(cohort.records),
    mostLimitingAssumption: buildMostLimitingAssumption(cohort.records),
    inputConfidenceTrend: buildInputConfidenceTrend(cohort, cohortMap),
  }));

  return {
    contractVersion: INVESTOR_INDEX_CONTRACT_VERSION,
    privacyPolicy: INVESTOR_INDEX_PRIVACY_POLICY,
    cohorts,
  };
}
