/**
 * GENERATED by scripts/capture-screenshots.ts — do not edit by hand.
 * Real product screenshots captured from the no-account sample flow; the
 * <ProductShot /> component reads intrinsic sizes from here. An empty list
 * means the pipeline has not run yet and every ProductShot renders nothing.
 */
export type ProductShotEntry = {
  shot: string;
  viewport: "desktop" | "mobile";
  width: number;
  height: number;
  png: string;
  webp: string;
  source: string;
  captured_at: string;
};

export const PRODUCT_SHOTS: readonly ProductShotEntry[] = [
  {
    "shot": "verdict",
    "viewport": "desktop",
    "width": 2464,
    "height": 2018,
    "png": "/product/verdict-desktop.png",
    "webp": "/product/verdict-desktop.webp",
    "source": "http://127.0.0.1:3100/analyze?sample=1",
    "captured_at": "2026-09-30T23:06:08.419Z"
  },
  {
    "shot": "where-the-rent-goes",
    "viewport": "desktop",
    "width": 2280,
    "height": 504,
    "png": "/product/where-the-rent-goes-desktop.png",
    "webp": "/product/where-the-rent-goes-desktop.webp",
    "source": "http://127.0.0.1:3100/analyze?sample=1",
    "captured_at": "2026-09-30T23:06:09.007Z"
  },
  {
    "shot": "memo",
    "viewport": "desktop",
    "width": 2560,
    "height": 4110,
    "png": "/product/memo-desktop.png",
    "webp": "/product/memo-desktop.webp",
    "source": "http://127.0.0.1:3100/sample-decision-memo",
    "captured_at": "2026-09-30T23:06:14.413Z"
  },
  {
    "shot": "verdict",
    "viewport": "mobile",
    "width": 716,
    "height": 2554,
    "png": "/product/verdict-mobile.png",
    "webp": "/product/verdict-mobile.webp",
    "source": "http://127.0.0.1:3100/analyze?sample=1",
    "captured_at": "2026-09-30T23:06:16.274Z"
  },
  {
    "shot": "where-the-rent-goes",
    "viewport": "mobile",
    "width": 612,
    "height": 762,
    "png": "/product/where-the-rent-goes-mobile.png",
    "webp": "/product/where-the-rent-goes-mobile.webp",
    "source": "http://127.0.0.1:3100/analyze?sample=1",
    "captured_at": "2026-09-30T23:06:16.835Z"
  },
  {
    "shot": "memo",
    "viewport": "mobile",
    "width": 780,
    "height": 6514,
    "png": "/product/memo-mobile.png",
    "webp": "/product/memo-mobile.webp",
    "source": "http://127.0.0.1:3100/sample-decision-memo",
    "captured_at": "2026-09-30T23:06:21.951Z"
  }
];
export const PRODUCT_SHOTS_GENERATED_AT: string | null = "2026-09-30T23:06:21.964Z";
